import test from 'node:test';import assert from 'node:assert/strict';import {registerAgentRuns} from './agentRuns';import {agentRuns,mediaJobs} from '../shared/schema';import{eq}from'drizzle-orm';
test('visual failure holds downstream work and reviewed plan repairs preserve successful work and the allowance',{skip:!process.env.PGLITE_MODULE},async()=>{
 const{PGlite}=await import(process.env.PGLITE_MODULE!);const{drizzle}=await import('drizzle-orm/pglite');const pg=new PGlite();const db=drizzle(pg);const old=process.env.CRON_SECRET;process.env.CRON_SECRET='test';
 await pg.exec(`CREATE TABLE users(id text primary key,email text,credits int);INSERT INTO users VALUES('owner','test@example.com',100);
 CREATE TABLE agent_runs(id text primary key,user_id text,project_id text,message_id text,persona_id text,status text,steps text,source_image text,error text,budget_credits int,used_credits int default 0,visual_review boolean default false,created_at timestamptz default now(),updated_at timestamptz default now());
 CREATE TABLE media_jobs(id text primary key,user_id text,agent_run_id text,persona_client_id text,kind text,status text,request text,result text,error text,model_id text,fallback_model_id text,attempt int default 0,used_fallback boolean default false,progress int default 0,stage text default 'Queued',cancel_requested boolean default false,created_at timestamptz default now(),started_at timestamptz,updated_at timestamptz default now(),completed_at timestamptz);`);
 const routes=new Map<string,Function>();const app={post:(p:string,f:Function)=>routes.set('POST '+p,f),get:(p:string,f:Function)=>routes.set('GET '+p,f)};let checks=0;let judgment='failed';
 const advance=registerAgentRuns(app,db,()=>{},async()=>[{id:'persona'}],async()=>({kind:'image',credits:3,providerCostMicrousd:50000,providerCostUsd:.05,provider:'test',quoteSource:'test',count:1}),undefined,{inspect:async()=>{checks++;return{status:judgment,summary:'The cup is still blue.',checkedAt:new Date().toISOString()};}});
 const call=async(path:string,body:any={},params:any={})=>{let code=200,data:any;await routes.get(path)!({body,params,user:{id:'owner'},query:{projectId:'default'}},{status(n:number){code=n;return this;},json(d:any){data=JSON.parse(JSON.stringify(d));return this;}});return{code,...data};};
 try{
 const created=await call('POST /api/agent-runs',{projectId:'default',messageId:'msg',personaId:'persona',budgetCredits:15,visualReview:true,steps:[{type:'generate_image',params:{prompt:'A green cup, no people'}},{type:'edit_image',params:{prompt:'Add a white saucer',sourceImageFromStepIndex:0}}]});assert.equal(created.code,200);assert.equal(created.run.budgetCredits,15,'approval must persist a firm allowance');
 const[job]=await db.select().from(mediaJobs);assert.equal(job.agentRunId,created.run.id);await db.update(mediaJobs).set({status:'succeeded',result:JSON.stringify({url:'https://example.com/blue.jpg'})}).where(eq(mediaJobs.id,job.id));await advance();
 const failed=(await call('GET /api/agent-runs')).runs[0];assert.equal(checks,1);assert.equal(failed.status,'failed');assert.equal(failed.steps[0].quality.status,'failed');assert.equal((await db.select().from(mediaJobs)).length,1,'bad output cannot feed a downstream step');await advance();assert.equal(checks,1,'polling cannot repeat a paid review');
 const details=await call('GET /api/agent-runs/:id/recovery',{}, {id:created.run.id});assert.equal(details.remainingSteps.length,2);
 const bad=await call('POST /api/agent-runs/:id/:action',{version:details.version,repairs:[{index:2,prompt:'Invalid index'}]},{id:created.run.id,action:'retry'});assert.equal(bad.code,409);
 const repaired=await call('POST /api/agent-runs/:id/:action',{version:details.version,repairs:[{index:0,prompt:'A vividly green ceramic cup, no people'},{index:1,prompt:'Add one white saucer under the green cup; keep the table'}]},{id:created.run.id,action:'retry'});assert.equal(repaired.code,200);assert.equal(repaired.run.steps[1].params.sourceImageFromStepIndex,0);assert.equal(repaired.run.steps[1].params.prompt,'Add one white saucer under the green cup; keep the table');assert.equal(repaired.run.budgetCredits,15);assert.equal((await db.select().from(mediaJobs)).length,2);
 // The allowance endpoint must succeed even when the saved run still has an error.
 await db.update(agentRuns).set({status:'failed',error:'Task allowance reached',usedCredits:14}).where(eq(agentRuns.id,created.run.id));
 assert.equal((await call('POST /api/agent-runs/:id/allowance',{budgetCredits:13},{id:created.run.id})).code,409);
 const raised=await call('POST /api/agent-runs/:id/allowance',{budgetCredits:20},{id:created.run.id});assert.equal(raised.code,200);assert.equal(raised.run.budgetCredits,20);assert.equal(raised.run.status,'failed');
 const resumed=await call('POST /api/agent-runs/:id/:action',{prompt:'A green cup',version:raised.run.updatedAt},{id:created.run.id,action:'retry'});assert.equal(resumed.code,200);
 judgment='passed';await db.update(mediaJobs).set({status:'succeeded',result:JSON.stringify({url:'https://example.com/green.jpg'})}).where(eq(mediaJobs.id,resumed.run.steps[0].jobId));await advance();
 const next=(await call('GET /api/agent-runs')).runs[0];assert.equal(next.steps[0].status,'success');assert.equal(next.steps[1].status,'running');assert.equal(JSON.parse((await db.select().from(mediaJobs).where(eq(mediaJobs.id,next.steps[1].jobId)))[0].request).sourceImage,'https://example.com/green.jpg');
 judgment='uncertain';await db.update(mediaJobs).set({status:'succeeded',result:JSON.stringify({url:'https://example.com/saucer.jpg'})}).where(eq(mediaJobs.id,next.steps[1].jobId));await advance();
 const review=await call('GET /api/agent-runs/:id/recovery',{}, {id:created.run.id});assert.equal(review.quality.status,'uncertain');assert.equal(review.resultUrl,'https://example.com/saucer.jpg');
 const count=(await db.select().from(mediaJobs)).length;
 assert.equal((await call('POST /api/agent-runs/:id/:action',{version:'stale'},{id:created.run.id,action:'accept-result'})).code,409);
 const accepted=await call('POST /api/agent-runs/:id/:action',{version:review.version},{id:created.run.id,action:'accept-result'});assert.equal(accepted.run.status,'succeeded');assert.equal(accepted.run.steps[0].resultUrl,'https://example.com/green.jpg');assert.equal(accepted.run.steps[1].quality.status,'accepted');assert.equal((await db.select().from(mediaJobs)).length,count,'acceptance never regenerates an image');

 }finally{if(old===undefined)delete process.env.CRON_SECRET;else process.env.CRON_SECRET=old;await pg.close();}
});
