import test from 'node:test';
import assert from 'node:assert/strict';
import { registerAgentRuns } from './agentRuns';
import { agentRuns, mediaJobs } from '../shared/schema';
import { eq } from 'drizzle-orm';
// Opt-in embedded PostgreSQL integration test, with no account/API credentials.
// PGLITE_MODULE points to an installed @electric-sql/pglite ESM entry point.
test('approved plan survives reconnect, advances once, pauses/resumes and isolates owners', { skip: !process.env.PGLITE_MODULE }, async () => {
    const previousSecret=process.env.CRON_SECRET;process.env.CRON_SECRET='synthetic-test';
    const { drizzle } = await import('drizzle-orm/pglite');
    const { PGlite } = await import(process.env.PGLITE_MODULE!);
    const pg = new PGlite();
    const db = drizzle(pg);
    await pg.exec(`CREATE TABLE users(id text primary key,email text,credits int default 0); INSERT INTO users(id,email) VALUES ('owner','owner@example.com'); CREATE TABLE agent_runs(budget_credits int,used_credits int default 0,visual_review boolean default false,id text primary key,user_id text not null,project_id text not null,message_id text not null,persona_id text not null,status text not null,steps text not null,source_image text,error text,created_at timestamptz default now(),updated_at timestamptz default now());
 CREATE TABLE media_jobs(agent_run_id text,id text primary key,user_id text,persona_client_id text,kind text,status text,request text,result text,error text,model_id text,fallback_model_id text,attempt int default 0,used_fallback boolean default false,progress int default 0,stage text default 'Queued',cancel_requested boolean default false,created_at timestamptz default now(),started_at timestamptz,updated_at timestamptz default now(),completed_at timestamptz);`);
    const routes = new Map<string, Function>();
    const app = { post: (p: string, f: Function) => routes.set('POST ' + p, f), get: (p: string, f: Function) => routes.set('GET ' + p, f) };
    const scheduled: any[] = [];
    let analysisCalls=0, changeDuringAnalysis=false, rejectAnalysis=false;
    let analysisStarted:(()=>void)|undefined, releaseAnalysis:(()=>void)|undefined;
    let analysisGate:Promise<void>|undefined;
    const advance = registerAgentRuns(app, db, (_id, _userId, user) => { scheduled.push(user); }, async () => [{ id: 'persona' }], async()=>({kind:'image',provider:'test',count:1,credits:3,providerCostUsd:.05,providerCostMicrousd:50000,quoteSource:'test'}), async (context:any,model:string)=>{
        analysisCalls++;
        assert.equal(context.steps[0].status,'success');
        assert.equal(context.steps[1].params.prompt,'Make the cup green');
        assert.equal(model,'frontier-gemini-flash');
        analysisStarted?.();
        if(analysisGate)await analysisGate;
        if(rejectAnalysis)throw new Error('Selected model unavailable');
        if(changeDuringAnalysis)await db.update(agentRuns).set({updatedAt:new Date('2026-09-14T22:00:00Z')});
        return {action:'revise',reason:'Make the color change explicit.',proposedPrompt:'Change only the cup to green',model:'test-model',provider:'test'};
    });
    const call = async (path: string, body: any = {}, user = 'owner', params: any = {}) => { let code = 200, result: any; await routes.get(path)!({ body, user: { id: user }, params, query: { projectId: 'default' } }, { status(n: number) { code = n; return this; }, json(v: any) { result = v; return this; } }); return { code, ...result }; };
    const body = { budgetCredits:100, visualReview:false, projectId: 'default', messageId: 'message', personaId: 'persona', steps: [{ type: 'generate_image', params: { prompt: 'A blue teacup, no people' } }, { type: 'edit_image', params: { prompt: 'Make the cup green', sourceImage: 'previous_result' } }] };
    try {
        const estimate = await call('POST /api/agent-runs/quote',body);
        assert.equal(estimate.insufficientCredits,true);
        assert.equal(estimate.complete,true);
        assert.equal((await db.select().from(mediaJobs)).length,0,'quoting never starts a generation');
        const denied = await call('POST /api/agent-runs', body);
        assert.equal(denied.code,402);
        assert.equal((await db.select().from(agentRuns)).length,0,'insufficient credit must not create a plan');
        assert.equal(scheduled.length,0,'insufficient credit must not schedule a job');
        await pg.exec("UPDATE users SET credits=10 WHERE id='owner'");
        const first = await call('POST /api/agent-runs', body);
        assert.equal(first.code, 200);
        const precision=await pg.query('SELECT (extract(microseconds from updated_at)::bigint % 1000) AS remainder FROM media_jobs');
        assert.equal(Number(precision.rows[0].remainder),0,'worker claim timestamps must round-trip through JavaScript');
        await pg.exec("UPDATE media_jobs SET updated_at = '2026-09-14 14:30:09.684752+00'");
        await pg.exec("UPDATE users SET credits=0 WHERE id='owner'");
        const second = await call('POST /api/agent-runs', body);
        const recoveredPrecision=await pg.query('SELECT (extract(microseconds from updated_at)::bigint % 1000) AS remainder FROM media_jobs');
        assert.equal(Number(recoveredPrecision.rows[0].remainder),0,'legacy queued timestamp must become claimable');
        assert.equal(second.run.id, first.run.id);
        assert.equal((await db.select().from(mediaJobs)).length, 1);
        assert.equal((await call('GET /api/agent-runs', {}, 'other')).runs.length, 0);
        assert.equal((await call('POST /api/agent-runs/:id/:action', {}, 'other', { id: first.run.id, action: 'stop' })).code, 404);
        await call('POST /api/agent-runs/:id/:action', {}, 'owner', { id: first.run.id, action: 'stop' });
        const jobs = await db.select().from(mediaJobs);
        await db.update(mediaJobs).set({ status: 'succeeded', result: JSON.stringify({ url: 'https://example.com/cup.jpg' }) }).where(eq(mediaJobs.id, jobs[0].id));
        await advance();
        assert.equal((await db.select().from(mediaJobs)).length, 1);
        await call('POST /api/agent-runs/:id/:action', {}, 'owner', { id: first.run.id, action: 'resume' });
        await pg.exec("DELETE FROM users WHERE id='owner'");
        const beforeMissingOwner = scheduled.length;
        await advance();
        assert.equal(scheduled.length, beforeMissingOwner, 'deleted accounts cannot schedule background work');
        await pg.exec("INSERT INTO users(id,email) VALUES ('owner','owner@example.com')");
        await advance();
        assert.equal(scheduled.at(-1)?.email, 'owner@example.com', 'background billing must receive canonical account email');
        await advance();
        const next = await db.select().from(mediaJobs);
        assert.equal(next.length, 2);
        const edit = next.find(j => j.kind === 'edit')!;
        assert.equal(JSON.parse(edit.request!).sourceImage, 'https://example.com/cup.jpg');
        await db.update(mediaJobs).set({ status: 'failed', error: 'Provider unavailable' }).where(eq(mediaJobs.id, edit.id));
        await advance();
        await advance();
        assert.equal((await db.select().from(mediaJobs)).length, 2);
        assert.equal((await call('GET /api/agent-runs')).runs[0].status, 'failed');
        const review=await call('GET /api/agent-runs/:id/recovery',{},'owner',{id:first.run.id});
        assert.equal(review.advice.kind,'temporary');
        assert.equal((await call('GET /api/agent-runs/:id/recovery',{},'other',{id:first.run.id})).code,404);
        assert.ok(routes.has('POST /api/agent-runs/:id/repair-proposal'),'failed plans must support a proposal without executing it');
        const propose=(version:string,user='owner')=>call('POST /api/agent-runs/:id/repair-proposal',{version,model:'frontier-gemini-flash'},user,{id:first.run.id});
        assert.equal((await propose(review.version,'other')).code,404);
        assert.equal((await propose('stale')).code,409);
        assert.equal(analysisCalls,0,'unauthorized or stale requests cannot incur model usage');
        const beforeProposal=(await db.select().from(agentRuns))[0];
        const proposal=await propose(review.version);
        assert.equal(proposal.code,200);
        assert.equal(proposal.proposal.proposedPrompt,'Change only the cup to green');
        assert.equal(proposal.version,review.version);
        assert.deepEqual((await db.select().from(agentRuns))[0],beforeProposal,'analysis cannot modify the plan');
        assert.equal((await db.select().from(mediaJobs)).length,2,'analysis cannot submit a generation');
        rejectAnalysis=true;
        assert.equal((await propose(review.version)).code,502);
        rejectAnalysis=false;
        const started=new Promise<void>(resolve=>{analysisStarted=resolve;});
        analysisGate=new Promise<void>(resolve=>{releaseAnalysis=resolve;});
        const pendingProposal=propose(review.version);
        await started;
        assert.equal((await propose(review.version)).code,429,'duplicate analysis on the active server cannot incur another model call');
        releaseAnalysis!();
        assert.equal((await pendingProposal).code,200,'provider failure must release the previous analysis lock');
        analysisGate=undefined;analysisStarted=undefined;
        changeDuringAnalysis=true;
        assert.equal((await propose(review.version)).code,409,'a proposal based on a concurrently changed plan must be rejected');
        changeDuringAnalysis=false;
        const freshReview=await call('GET /api/agent-runs/:id/recovery',{},'owner',{id:first.run.id});
        const stale=await call('POST /api/agent-runs/:id/:action',{prompt:'Make cup green',version:'stale'},'owner',{id:first.run.id,action:'retry'});
        assert.equal(stale.code,409);
        await call('POST /api/agent-runs/:id/:action', {prompt:proposal.proposal.proposedPrompt,version:freshReview.version}, 'owner', { id: first.run.id, action: 'retry' });
        const retried = (await db.select().from(mediaJobs)).find(j => j.id !== edit.id && j.id !== jobs[0].id)!;
        assert.ok(retried);
        assert.equal(JSON.parse(retried.request!).prompt,'Change only the cup to green');
        assert.equal(JSON.parse(retried.request!).sourceImage, 'https://example.com/cup.jpg');
        await db.update(mediaJobs).set({ status: 'succeeded', result: JSON.stringify({ url: 'https://example.com/green.jpg' }) }).where(eq(mediaJobs.id, retried.id));
        await advance();
        await advance();
        const saved = await call('GET /api/agent-runs');
        assert.equal(saved.runs[0].status, 'succeeded');
        assert.equal(saved.runs[0].steps[1].resultUrl, 'https://example.com/green.jpg');
        assert.equal((await db.select().from(mediaJobs)).length, 3);
    }
    finally {
        if(previousSecret===undefined)delete process.env.CRON_SECRET;else process.env.CRON_SECRET=previousSecret;
        await pg.close();
    }
});
