import test from 'node:test';import assert from 'node:assert/strict';import{Jimp}from'jimp';import{inspectAgentImage}from'./agentVisual';
async function fixture(color:number){const i=new Jimp({width:8,height:8,color});return 'data:image/png;base64,'+(await i.getBuffer('image/png')).toString('base64');}
test('identical source pixels fail before any model call without a paid visual assessment',async()=>{const image=await fixture(0x0000ffff);let calls=0;const report=await inspectAgentImage({output:image,source:image,prompt:'Change blue cup to green'},async()=>{calls++;return '{}';});assert.equal(report.status,'failed');assert.equal(calls,0);});
test('visual inspection sends output and reference pixels; a confident mismatch blocks the plan',async()=>{const output=await fixture(0x0000ffff),source=await fixture(0x00ff00ff);const result=await inspectAgentImage({output,source,prompt:'Change blue cup to green',references:[{name:'Saved subject',image:source}]},async(parts:any[])=>{assert.equal(parts.filter(p=>p.inlineData).length,3);return JSON.stringify({matchesRequest:false,referenceConsistent:true,editApplied:false,confidence:.95,summary:'Requested green, but cup remains blue.'});});assert.equal(result.status,'failed');assert.match(result.summary,/blue/);});
test('uncertain, malformed or incomplete visual judgments cannot pass',async()=>{const output=await fixture(0x0000ffff);for(const value of ['{}','not JSON',JSON.stringify({matchesRequest:true,referenceConsistent:null,editApplied:null,confidence:.4,summary:'Unclear'})])assert.equal((await inspectAgentImage({output,prompt:'A cup'},async()=>value)).status,'uncertain');});
test('a complete confident judgment may pass; private reference URLs are rejected',async()=>{const output=await fixture(0x0000ffff);assert.equal((await inspectAgentImage({output,prompt:'A blue cup'},async()=>JSON.stringify({matchesRequest:true,referenceConsistent:null,editApplied:null,confidence:.9,summary:'Blue cup matches the instruction.'}))).status,'passed');await assert.rejects(inspectAgentImage({output:'https://127.0.0.1/image.png',prompt:'cup'},async()=>''));});

test('allowance and provider failures remain actionable instead of being hidden as malformed model output',async()=>{await assert.rejects(inspectAgentImage({output:await fixture(0x0000ffff),prompt:'Blue square'},async()=>{throw new Error('Task allowance reached');}),/Task allowance reached/);});

test('compressed images with oversized dimensions are rejected before decoding',async()=>{const data=Buffer.alloc(24);Buffer.from([137,80,78,71,13,10,26,10]).copy(data);data.write('IHDR',12);data.writeUInt32BE(100000,16);data.writeUInt32BE(100000,20);await assert.rejects(inspectAgentImage({output:'data:image/png;base64,'+data.toString('base64'),prompt:'test'},async()=>''),/resolution is too large/);});

test('duplicate PNG headers cannot override the validated dimensions',async()=>{const small=Buffer.from((await fixture(0x0000ffff)).split(',')[1],'base64');const duplicate=Buffer.concat([small.subarray(0,33),small.subarray(8)]);await assert.rejects(inspectAgentImage({output:'data:image/png;base64,'+duplicate.toString('base64'),prompt:'blue square'},async()=>''),/Duplicate or invalid PNG/);});
