import React,{useState,useEffect,useRef} from 'react';
import {Persona} from '../types';
import {authFetch} from '../services/imageService';
import {processImageFile} from '../utils/imageProcessing';
import {CAROUSEL_FORMATS,CarouselFormat,CarouselSlide,carouselZip,validateCarousel,normalizeSlideDesign,CarouselLayout,packCarouselImages,unpackCarouselImages} from '../../shared/carousel';
import {renderCarouselSlide,saveCarouselFile,CarouselTheme} from '../utils/carouselRenderer';

import CarouselSequenceStudio from './CarouselSequenceStudio';
import CarouselPhotoPicker from './CarouselPhotoPicker';
import CarouselDesignControls,{LAYOUTS} from './CarouselDesignControls';

function DesignPreview({theme,image,layout='editorial',photosOnly=false}:{photosOnly?:boolean;theme:CarouselTheme;image?:string;layout?:CarouselLayout}) {
 const [src,setSrc]=useState('');
 useEffect(()=>{let cancelled=false;renderCarouselSlide({headline:'Your story starts here',body:'One idea. A clear next step.',image,layout},0,5,'instagram',theme,'YOUR PERSONA',photosOnly).then(c=>{if(!cancelled)setSrc(c.toDataURL('image/jpeg',.8));}).catch(()=>{if(!cancelled)setSrc('');});return()=>{cancelled=true};},[theme,image,layout,photosOnly]);
 return src?<img src={src} alt="" className="w-full h-32 sm:h-48 object-contain rounded-lg"/>:<div className="h-32 sm:h-48 rounded-lg bg-white/10"/>;
}

export default function CarouselCreator({persona}:{persona:Persona}){
 const [coverUse,setCoverUse]=useState<'finished'|'reference'>('finished');
 const [workspace,setWorkspace]=useState<'photos'|'ai'|'design'|'export'>('photos');
 const [photosOnly,setPhotosOnly]=useState(false);
 const [format,setFormat]=useState<CarouselFormat>('instagram'),[theme,setTheme]=useState<CarouselTheme>('midnight');
 const [topic,setTopic]=useState(''),[count,setCount]=useState(5),[slides,setSlides]=useState<CarouselSlide[]>([]),[caption,setCaption]=useState(''),[selected,setSelected]=useState(0);
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState(''),[previewError,setPreviewError]=useState('');
 const [layout,setLayout]=useState<CarouselLayout>('editorial'),[safeAreas,setSafeAreas]=useState(false),[referenceAdvice,setReferenceAdvice]=useState('');
 const referenceUpload=useRef<HTMLInputElement>(null);
 const [uploadedPhotos,setUploadedPhotos]=useState<string[]>([]);
 const sourceUpload=useRef<HTMLInputElement>(null);
 const request=useRef(0),upload=useRef<HTMLInputElement>(null),restore=useRef<HTMLInputElement>(null);
 useEffect(()=>()=>{request.current++;},[]);
 const photos=[...new Set([...uploadedPhotos,persona.referenceImage,persona.avatar,...(persona.additionalReferenceImages||[]),...(persona.visualLibrary||[]).map(i=>i.url)].filter((x):x is string=>!!x))];
 const startingPhotos=uploadedPhotos.length?uploadedPhotos:photos;
 const slide=slides[selected];
 useEffect(()=>{let cancelled=false;setPreview('');setPreviewError('');if(slide)renderCarouselSlide(slide,selected,slides.length,format,theme,persona.name,photosOnly).then(c=>{if(!cancelled)setPreview(c.toDataURL('image/jpeg',.92));}).catch(e=>{if(!cancelled)setPreviewError(e.message)});return()=>{cancelled=true};},[slide,selected,slides.length,format,theme,persona.name,photosOnly]);
 const update=(patch:Partial<CarouselSlide>)=>setSlides(s=>s.map((v,i)=>i===selected?{...v,...patch}:v));
 const generate=async()=>{const id=++request.current;setBusy('Generating slides…');setError('');try{
 const r=await authFetch('/api/carousel-content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({persona,topic,count:slides.length||count,format,layout})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Generation failed. Try again.');const valid=validateCarousel(data,slides.length||count);if(id===request.current){setSlides(previous=>valid.slides.map((s,i)=>({...previous[i],...s,layout:previous[i]?.layout||layout,image:previous[i]?.image,secondImage:previous[i]?.secondImage})));setCaption(valid.caption);setSelected(0);setWorkspace('design');}
 }catch(e:any){if(id===request.current)setError(e.message);}finally{if(id===request.current)setBusy('');}};
 const project=()=>({version:2,format,theme,layout,photosOnly,...packCarouselImages(slides),caption,topic});
 const exportAll=async()=>{setBusy('Preparing export…');setError('');try{const files:{name:string;data:Uint8Array}[]=[];for(let i=0;i<slides.length;i++){const canvas=await renderCarouselSlide(slides[i],i,slides.length,format,theme,persona.name,photosOnly);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Image export failed.')),'image/jpeg',.94));files.push({name:`${String(i+1).padStart(2,'0')}-slide.jpg`,data:new Uint8Array(await blob.arrayBuffer())});}
 const enc=new TextEncoder();files.push(...(!photosOnly?[{name:'caption.txt',data:enc.encode(caption)}]:[]),{name:'alt-text.txt',data:enc.encode(slides.map((s,i)=>`Slide ${i+1}: ${s.alt||(photosOnly?'':s.headline+' — '+s.body)}`).join('\n\n'))},{name:'carousel-project.json',data:enc.encode(JSON.stringify(project()))},{name:'posting-guide.txt',data:enc.encode(format==='instagram'?'Extract this ZIP. Upload the numbered JPGs in order as one Instagram post. Keep the same crop for every slide. Add an optional caption, review alt text, and add music in Instagram if desired.':'Extract this ZIP. In TikTok tap +, Upload, select the numbered JPGs in order, then use photo mode. Add an optional caption and music in TikTok. Preview placement before posting; app controls may cover edges.')});
 saveCarouselFile(new Blob([carouselZip(files) as BlobPart],{type:'application/zip'}),`${format}-carousel.zip`);
 }catch(e:any){setError(e.message);}finally{setBusy('');}};
 const move=(delta:number)=>{const to=selected+delta;if(to<0||to>=slides.length)return;setSlides(s=>{const next=[...s];[next[selected],next[to]]=[next[to],next[selected]];return next;});setSelected(to);};
 const startProject=(kind:'photos'|'ai'|'guide')=>{
  const photoMode=kind!=='guide';setPhotosOnly(photoMode);setLayout(photoMode?'full-photo':'editorial');
  setSlides(Array.from({length:count},(_,i)=>({headline:'',body:'',layout:photoMode?'full-photo':'editorial',image:kind==='ai'?(i===0?startingPhotos[0]:undefined):startingPhotos[i%startingPhotos.length]})));
  setCaption('');setSelected(0);setWorkspace(kind==='ai'?'ai':kind==='guide'?'design':'photos');
 };
 return <fieldset disabled={!!busy} className="space-y-6 min-w-0 pb-8">
 {slides.length===0&&<header className="flex flex-wrap justify-between items-start gap-4"><div><h2 className="text-2xl sm:text-3xl font-semibold text-white">{slides.length?'Your carousel':'One post. A story worth swiping.'}</h2><p className="text-sm text-slate-400 mt-2 max-w-xl">{slides.length?`${slides.length} slides for ${format==='instagram'?'Instagram':'TikTok'} · ${photosOnly?'Photos only':'Photos and text'}`:'A carousel is a post with multiple photos or slides that people swipe through. Start with your own photos, generate new ones, or turn an idea into a visual guide.'}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>restore.current?.click()} className="btn-gold-secondary px-3 py-2 text-xs">Open project</button>{slides.length>0&&<button type="button" onClick={()=>saveCarouselFile(new Blob([JSON.stringify(project())],{type:'application/json'}),'carousel-project.json')} className="btn-gold-secondary px-3 py-2 text-xs">Save project</button>}</div></header>}
  <input ref={restore} type="file" accept="application/json,.json" className="hidden" onChange={async e=>{setBusy("Opening project…");try{const f=e.target.files?.[0];if(!f)return;if(f.size>100000000)throw new Error('This project is too large.');const d=JSON.parse(await f.text());if(![1,2].includes(d.version)||!['instagram','tiktok'].includes(d.format)||!['midnight','paper','photo'].includes(d.theme)||!Array.isArray(d.slides)||d.slides.length<2||d.slides.length>10)throw new Error('Choose a carousel-project.json exported by this tool.');const v=validateCarousel(d,d.slides.length,true);setSlides(v.slides.map((s,i)=>({...s,...unpackCarouselImages(d.slides[i],d.assets)})));setLayout(normalizeSlideDesign({layout:d.layout}).layout||'editorial');setPhotosOnly(d.photosOnly===true);setCaption(v.caption);setFormat(d.format);setTheme(d.theme);setSelected(0);setTopic(String(d.topic||'').slice(0,5000));setWorkspace('photos');setError('');}catch(err:any){setError(err.message);}finally{setBusy('');}e.target.value='';}}/>

 {busy&&<p role="status" className="sticky top-4 z-20 rounded-xl bg-[#E7C477] text-black p-3 text-sm shadow-lg">{busy}</p>}{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}
 {slides.length===0?<section className="space-y-6">
 <div className="rounded-2xl bg-white/[.035] p-3 sm:p-4">  <div className="grid grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)] gap-3">
   <label className="min-w-0 text-xs text-slate-300">Platform<select value={format} onChange={e=>setFormat(e.target.value as CarouselFormat)} className="luxury-input mt-1.5 h-11 w-full min-w-0 px-2 sm:px-3 text-sm">{Object.entries(CAROUSEL_FORMATS).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label>
   <label className="min-w-0 text-xs text-slate-300">Number of slides<select value={count} onChange={e=>setCount(+e.target.value)} className="luxury-input mt-1.5 h-11 w-full min-w-0 px-2 sm:px-3 text-sm">{Array.from({length:9},(_,i)=>i+2).map(n=><option key={n}>{n}</option>)}</select></label>
  </div>
</div>
 <div className="grid sm:grid-cols-3 gap-4">{([
  {id:'photos',title:'Use my photos',text:'Arrange your photos into a swipeable post. No text needed.',image:startingPhotos[0]||'/examples/showcase_parisian_chic.png'},
  {id:'ai',title:'Generate with AI',text:'Create a cover, plan the next shots, and choose your image model.',image:'/examples/showcase_haute_couture.png'},
  {id:'guide',title:'Turn an idea into slides',text:'Make a story, a useful guide, or a list with photos and text.',image:'/demo/carousel-creator.svg'}
 ] as const).map(k=><button type="button" key={k.id} onClick={()=>startProject(k.id)} className="group text-left overflow-hidden rounded-2xl border border-white/15 hover:border-[#E7C477] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#E7C477] transition-colors"><img src={k.image} alt="" className="w-full h-44 object-cover"/><span className="block p-5"><strong className="block text-lg text-white">{k.title}</strong><span className="block text-sm text-slate-400 mt-2">{k.text}</span></span></button>)}</div>
 <p className="text-xs text-slate-400">Already have a saved carousel? Open your project above. You can change photos, add text, or use AI at any point.</p>
 </section>:<>

 <div role="tablist" aria-label="Carousel workspace" className="flex border-b border-white/15 gap-1 overflow-x-auto">{([['photos','Photos'],['ai','AI sequence'],['design','Design'],['export','Export']] as const).map(([id,label])=><button type="button" role="tab" tabIndex={workspace===id?0:-1} onKeyDown={e=>{const names=['photos','ai','design','export'] as const;const n=names.indexOf(workspace);const next=e.key==='ArrowRight'?(n+1)%4:e.key==='ArrowLeft'?(n+3)%4:e.key==='Home'?0:e.key==='End'?3:-1;if(next>=0){e.preventDefault();setWorkspace(names[next]);(e.currentTarget.parentElement?.querySelectorAll('button')[next] as HTMLButtonElement)?.focus();}}} aria-selected={workspace===id} aria-controls={`carousel-panel-${id}`} id={`carousel-tab-${id}`} key={id} onClick={()=>setWorkspace(id)} className={`px-5 py-3 text-sm whitespace-nowrap border-b-2 ${workspace===id?'border-[#E7C477] text-[#E7C477]':'border-transparent text-slate-400 hover:text-white'}`}>{label}</button>)}</div>
 {workspace!=='export'&&<div className="flex items-end gap-3"><label className="text-xs text-slate-300">Editing slide<select aria-label="Editing slide" value={selected} onChange={e=>setSelected(+e.target.value)} className="luxury-input block h-11 mt-1 px-3 text-sm">{slides.map((_,i)=><option key={i} value={i}>{i===0?'Cover (slide 1)':`Slide ${i+1}`}</option>)}</select></label><button type="button" disabled={slides.length>=10} onClick={()=>{setSlides(s=>[...s,{headline:'',body:'',layout:photosOnly?'full-photo':'editorial'}]);setSelected(slides.length);}} className="text-xs text-slate-300 h-11 disabled:opacity-30">+ Add slide</button></div>}
 <section id="carousel-panel-photos" role="tabpanel" aria-labelledby="carousel-tab-photos" hidden={workspace!=='photos'} className="space-y-5"><div><h3 className="text-lg font-semibold">Choose the photos</h3><p className="text-sm text-slate-400 mt-1">Choose a photo for the selected slide. The cover is the first photo people see.</p></div>  <section className="rounded-xl border border-white/15 p-4 space-y-3" aria-label="Carousel photos">
   <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold text-white">Add your photos</h3><p className="text-xs text-slate-400 mt-1">Add up to 10 photos, then choose where each one goes.</p></div><button type="button" onClick={()=>sourceUpload.current?.click()} className="btn-gold-primary px-4 py-2 text-sm">Upload photos</button></div>
   <input ref={sourceUpload} type="file" accept="image/*" multiple className="hidden" aria-label="Upload carousel photos" onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;setBusy('Loading photos…');setError('');try{if(files.length+uploadedPhotos.length>10)throw new Error('You can add up to 10 photos. Remove a photo before adding more.');const images:string[]=[];for(const f of files)images.push(await processImageFile(f));setUploadedPhotos(p=>[...p,...images]);}catch(err:any){setError(err.message||'Could not load the photos.');}finally{setBusy('');}}}/>
   {uploadedPhotos.length>0?<><div className="flex gap-3 overflow-x-auto">{uploadedPhotos.map((src,i)=><div key={i} className="shrink-0 w-24"><img src={src} alt={`Uploaded photo ${i+1}`} style={{aspectRatio:format==='instagram'?'4 / 5':'9 / 16'}} className="w-24 rounded-lg object-cover"/><button type="button" onClick={()=>setUploadedPhotos(p=>p.filter((_,n)=>n!==i))} className="text-xs text-slate-300 mt-2">Remove photo {i+1}</button></div>)}</div>{slides.length>0&&<button type="button" onClick={()=>setSlides(s=>s.map((v,i)=>({...v,image:uploadedPhotos[i%uploadedPhotos.length]})))} className="btn-gold-secondary px-3 py-2 text-xs">Apply uploaded photos to existing slides</button>}</>:<p className="text-xs text-slate-400">Your saved persona photos are available in the photo picker below.</p>}
  </section>
</section>
 <section id="carousel-panel-ai" role="tabpanel" aria-labelledby="carousel-tab-ai" hidden={workspace!=='ai'}><CarouselSequenceStudio selected={selected} onSelect={setSelected} photos={photos} persona={persona} slides={slides} format={format} onBusy={setBusy} onUpdate={(index,patch)=>setSlides(s=>s.map((v,i)=>i===index?{...v,...patch}:v))}/></section>
 <section id="carousel-panel-design" role="tabpanel" aria-labelledby="carousel-tab-design" hidden={workspace!=='design'} className="space-y-5"><div><h3 className="text-lg font-semibold">Make it yours</h3><p className="text-sm text-slate-400 mt-1">Style the selected slide. Photo-only posts keep every image free of text.</p></div>  <label className="flex items-start gap-3 rounded-xl border border-[#E7C477]/40 p-4"><input type="checkbox" checked={photosOnly} onChange={e=>{const enabled=e.target.checked;setPhotosOnly(enabled);if(enabled){if(['minimal','editorial'].includes(layout))setLayout('full-photo');setSlides(s=>s.map(v=>!v.layout||['minimal','editorial'].includes(v.layout)?{...v,layout:'full-photo'}:v));}}} className="mt-1 accent-[#E7C477]"/><span><strong className="block text-sm">Photos only</strong><span className="block text-xs text-slate-400 mt-1">Create a carousel with just your images. No hook, text, branding, slide numbers, or caption required.</span></span></label>

 {!photosOnly&&<details open={slides.every(s=>!s.headline.trim())} className="border-b border-white/15 pb-4"><summary className="cursor-pointer text-sm font-medium text-[#E7C477]">Write slide text with AI</summary><div className="space-y-3 mt-3"><label className="block text-xs">What is your post about?<textarea value={topic} onChange={e=>setTopic(e.target.value)} maxLength={5000} rows={3} className="luxury-input w-full mt-2 p-3" placeholder="Five things I wish I knew before starting strength training"/></label><button type="button" disabled={!topic.trim()} onClick={generate} className="btn-gold-secondary px-3 py-2 text-sm">Generate text for all slides</button><p className="text-xs text-slate-400">Replaces current slide text and caption.</p></div></details>}
 <details className="border-b border-white/15 pb-4"><summary className="cursor-pointer text-sm font-medium">Templates and colors for the whole carousel</summary><div className="space-y-6 mt-4">  <section aria-label="Slide design" className="space-y-3"><h3 className="text-sm font-semibold text-white">Choose a design</h3><div className="grid grid-cols-3 gap-2 sm:gap-4">{([
   {id:'midnight',name:'Dark background',description:'Photo above cream text on a dark background.'},
   {id:'paper',name:'Light background',description:'Photo above dark text on a warm light background.'},
   {id:'photo',name:'Photo background',description:'Full-slide photo with text over a dark overlay.'},
  ] as const).map(d=><button key={d.id} type="button" aria-pressed={theme===d.id} onClick={()=>setTheme(d.id)} className={`min-w-0 rounded-xl border p-2 sm:p-3 text-left ${theme===d.id?'border-[#E7C477] bg-[#E7C477]/10':'border-white/15'}`}><DesignPreview photosOnly={photosOnly} theme={d.id} image={startingPhotos[0] || '/examples/showcase_parisian_chic.png'}/><span className="block text-xs sm:text-sm font-semibold text-white mt-3">{d.name}{theme===d.id?' ✓':''}</span><span className="block text-[11px] sm:text-xs text-slate-400 mt-1">{photosOnly?'Background color for collage layouts. Full-frame photos fill the slide.':d.description}</span></button>)}</div></section>
  <section className="space-y-3" aria-label="Carousel layouts"><h3 className="font-semibold">Choose your layout</h3><p className="text-xs text-slate-400">Use these for photo dumps, lookbooks, story reveals, comparisons, rankings, or useful mini guides.</p><div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{LAYOUTS.filter(l=>!photosOnly||!['minimal','editorial'].includes(l.id)).map(l=><button type="button" key={l.id} aria-pressed={layout===l.id} onClick={()=>{setLayout(l.id);}} className={`rounded-xl border p-3 text-left ${layout===l.id?'border-[#E7C477] bg-[#E7C477]/10':'border-white/15'}`}><DesignPreview photosOnly={photosOnly} layout={l.id} theme={theme} image={startingPhotos[0]||'/examples/showcase_parisian_chic.png'}/><span className="block text-sm font-semibold mt-2">{l.name}</span><span className="block text-xs text-slate-400 mt-1">{photosOnly&&l.id==='full-photo'?'Your photo fills the entire slide.':l.description}</span></button>)}</div>{slides.length>0&&<button type="button" className="btn-gold-secondary px-3 py-2 text-xs" onClick={()=>setSlides(s=>s.map((v,i)=>({...v,layout,image:layout==='panorama'?s[0].image:v.image,...(layout==='panorama'?{cropX:s[0].cropX,cropY:s[0].cropY,zoom:s[0].zoom}:{}),secondImage:v.secondImage||startingPhotos[(i+1)%startingPhotos.length]})))}>Apply selected layout to existing slides</button>}</section>
</div></details>
 <details className="border-b border-white/15 pb-4"><summary className="cursor-pointer text-sm font-medium">Get design advice from a screenshot</summary><div className="mt-4">  <section className="border border-white/15 rounded-xl p-4 space-y-3"><h3 className="font-semibold">Inspired by a carousel?</h3><p className="text-xs text-slate-400">Upload a screenshot. Your existing Gemini connection will suggest a layout, photo treatment, and writing approach. Your photos and text stay your own. Uses your existing API credits.</p><button type="button" onClick={()=>referenceUpload.current?.click()} className="btn-gold-secondary px-3 py-2 text-xs">Analyze a reference screenshot</button><input ref={referenceUpload} type="file" accept="image/*" className="hidden" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;setBusy('Analyzing reference…');setError('');try{const image=await processImageFile(f);const r=await authFetch('/api/carousel-reference',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not analyze reference.');setReferenceAdvice(d.advice);const suggested=normalizeSlideDesign(d).layout||'editorial';setLayout(photosOnly&&['editorial','minimal'].includes(suggested)?'full-photo':suggested);}catch(err:any){setError(err.message);}finally{setBusy('');}}}/>{referenceAdvice&&<p className="text-sm text-slate-300 whitespace-pre-line">{referenceAdvice}</p>}</section>
</div></details>
 </section>
 {(workspace==='photos'||workspace==='design')&&slide&&<>   <div className="grid lg:grid-cols-2 gap-6 items-start">
    <div className="space-y-3 lg:sticky lg:top-24"><label className="flex gap-2 text-xs"><input type="checkbox" checked={safeAreas} onChange={e=>setSafeAreas(e.target.checked)}/>Show approximate safe area (preview only)</label><div className="relative mx-auto" style={{maxWidth:format==='instagram'?'calc(65vh * 0.8)':'calc(65vh * 0.5625)'}}>{safeAreas&&preview&&<div className="pointer-events-none absolute border-2 border-dashed border-cyan-300 z-10" style={{left:"7.4%",right:format==='tiktok'?"18.5%":"7.4%",top:format==='tiktok'?"9.4%":"6.3%",bottom:format==='tiktok'?"16.1%":"7.4%"}}/>}{preview?<img src={preview} alt={`Slide ${selected+1} preview: ${slide.headline}`} className="w-full rounded-xl border border-white/15 bg-black/30"/>:<div className="rounded-xl bg-white/5 p-6 text-sm text-slate-400">{previewError||'Rendering slide…'}</div>}</div><p className="text-xs text-slate-400">{CAROUSEL_FORMATS[format].width} × {CAROUSEL_FORMATS[format].height} JPG · {format==='tiktok'?'Extra space around text for app controls.':'Portrait feed layout.'}</p></div>
    <div className="space-y-4">{workspace==='design'&&!photosOnly&&<><label className="block text-xs text-slate-300">Headline ({slide.headline.length}/90)<textarea value={slide.headline} onChange={e=>update({headline:e.target.value})} maxLength={90} rows={2} className="luxury-input mt-2 p-3 w-full"/></label><label className="block text-xs text-slate-300">Body ({slide.body.length}/240)<textarea value={slide.body} onChange={e=>update({body:e.target.value})} maxLength={240} rows={4} className="luxury-input mt-2 p-3 w-full"/></label></>}
     {workspace==='photos'&&<>     {selected===0&&<div className="space-y-2"><h4 className="font-semibold text-sm">How will you use this photo?</h4><div className="grid gap-2 sm:grid-cols-2"><button type="button" aria-pressed={coverUse==='finished'} onClick={()=>setCoverUse('finished')} className={`text-left rounded-xl border p-3 text-sm ${coverUse==='finished'?'border-[#E7C477] text-[#E7C477]':'border-white/20'}`}>Use as the first slide<span className="block text-xs text-slate-400 mt-1">This photo will appear in your carousel.</span></button><button type="button" aria-pressed={coverUse==='reference'} onClick={()=>setCoverUse('reference')} className={`text-left rounded-xl border p-3 text-sm ${coverUse==='reference'?'border-[#E7C477] text-[#E7C477]':'border-white/20'}`}>Use as an AI reference<span className="block text-xs text-slate-400 mt-1">Generate a different first slide using this person.</span></button></div></div>}
     <CarouselPhotoPicker format={format} emptyLabel={selected===0&&coverUse==='reference'?'Use persona reference':'No photo'} label={selected===0?(coverUse==='reference'?'Reference for a new first slide':'Photo to use as the first slide'):`Photo for slide ${selected+1}`} photos={photos} value={selected===0&&coverUse==='reference'?(slide.coverReference||persona.referenceImage||persona.avatar||persona.alternateReferenceImage):slide.image} onChange={image=>update(selected===0&&coverUse==='reference'?{coverReference:image}:{image})}/>
     {selected===0&&coverUse==='reference'&&<p className="text-xs text-slate-400">Your current first slide stays unchanged. Continue to choose styling, write a prompt, and generate a new image.</p>}
     <button type="button" onClick={()=>upload.current?.click()} className="btn-gold-secondary px-3 py-2 text-xs">{selected===0?(coverUse==='reference'?'Upload an AI reference':'Upload the first-slide photo'):'Upload this slide’s photo'}</button><input ref={upload} type="file" accept="image/*" className="hidden" onChange={async e=>{const target=selected;const asReference=selected===0&&coverUse==='reference';setBusy("Loading photo…");try{const f=e.target.files?.[0];if(!f)return;const image=await processImageFile(f);setSlides(s=>s.map((v,i)=>i===target?{...v,...(asReference?{coverReference:image}:{image})}:v));}catch(err:any){setError(err.message||'Could not load photo.');}finally{setBusy('');}e.target.value='';}}/>
</>}
     {workspace==='design'&&<>     <CarouselDesignControls format={format} photosOnly={photosOnly} slide={slide} photos={photos} onChange={update} onPanorama={()=>setSlides(s=>s.map(v=>({...v,layout:'panorama',image:slide.image,cropX:slide.cropX,cropY:slide.cropY,zoom:slide.zoom})))}/>
</>}
     <details className="text-xs text-slate-400"><summary className="cursor-pointer py-2">Accessibility description (optional)</summary><label className="block text-xs text-slate-300">Image description / alt text<textarea value={slide.alt||''} onChange={e=>update({alt:e.target.value})} maxLength={400} rows={2} className="luxury-input mt-2 p-3 w-full"/></label></details>
     <p className="text-xs text-slate-400">Slide order: this is position {selected+1} of {slides.length}. Moving it changes the order people swipe through; position 1 is the cover.</p><div className="flex gap-3 flex-wrap"><button type="button" disabled={selected===0||!!busy} onClick={()=>move(-1)} className="text-xs text-slate-300 disabled:opacity-30">{selected===0?'Already first':`Move to position ${selected}`}</button><button type="button" disabled={selected===slides.length-1||!!busy} onClick={()=>move(1)} className="text-xs text-slate-300 disabled:opacity-30">{selected===slides.length-1?'Already last':`Move to position ${selected+2}`}</button><button type="button" disabled={slides.length<=2||!!busy} onClick={()=>{setSlides(s=>s.filter((_,i)=>i!==selected));setSelected(Math.max(0,selected-1));}} className="text-xs text-red-300 disabled:opacity-30">Remove slide</button></div>
    </div>
   </div>
</>}
 <section id="carousel-panel-export" role="tabpanel" aria-labelledby="carousel-tab-export" hidden={workspace!=='export'} className="space-y-5 max-w-3xl"><h3 className="text-xl font-semibold">Ready to share?</h3><p className="text-sm text-slate-400">Download your slides, then upload them together as one post. Your carousel is not posted automatically.</p>  <div className="grid gap-4 sm:grid-cols-2">
   <label className="text-xs text-slate-300">Platform<select value={format} onChange={e=>setFormat(e.target.value as CarouselFormat)} className="luxury-input mt-2 w-full p-3">{Object.entries(CAROUSEL_FORMATS).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label>
   <label className="text-xs text-slate-300 hidden">Project size<select value={count} onChange={e=>setCount(+e.target.value)} className="luxury-input mt-2 w-full p-3">{Array.from({length:9},(_,i)=>i+2).map(n=><option key={n}>{n}</option>)}</select></label>
  </div>
   {!photosOnly&&<label className="block text-xs text-slate-300">Post caption<textarea value={caption} onChange={e=>setCaption(e.target.value)} maxLength={2200} rows={4} className="luxury-input mt-2 p-3 w-full"/></label>}
   <div className="flex flex-wrap gap-3"><button type="button" disabled={!!busy} onClick={exportAll} className="btn-gold-primary px-5 py-3 text-sm disabled:opacity-50">Download all slides (.zip)</button><button type="button" onClick={()=>saveCarouselFile(new Blob([JSON.stringify(project())],{type:'application/json'}),'carousel-project.json')} className="btn-gold-secondary px-4 py-3 text-xs">Save editable project</button></div>
   <p className="text-xs text-slate-400">{photosOnly?'The ZIP includes numbered JPGs, optional alt text, and your editable project.':'The ZIP includes numbered JPGs, caption, alt text, and your editable project.'} Extract it before uploading. Add music inside Instagram or TikTok and check the final crop before posting. Save your project before closing this tool.</p>
</section>
 <footer className="flex justify-between items-center gap-3 pt-3 border-t border-white/10"><details className="text-xs text-slate-400"><summary className="cursor-pointer">Project options</summary><div className="flex flex-wrap gap-3 py-3"><button type="button" onClick={()=>restore.current?.click()}>Open project</button><button type="button" onClick={()=>saveCarouselFile(new Blob([JSON.stringify(project())],{type:'application/json'}),'carousel-project.json')}>Save project</button></div></details>{workspace!=='export'&&<button type="button" onClick={()=>{const next=workspace==='photos'&&coverUse==='reference'?'ai':workspace==='design'?'export':'design';if(next==='ai')setSelected(0);setWorkspace(next);const tab=document.getElementById(`carousel-tab-${next}`);tab?.focus();tab?.scrollIntoView({block:'center'});}} className="btn-gold-primary px-4 py-2 text-sm">Continue</button>}</footer>
 </>}
 </fieldset>;
}
