import React,{useRef,useState} from 'react';
import CarouselPhotoPicker from './CarouselPhotoPicker';
import {COVER_LIBRARY,CoverChoices} from '../../shared/carouselCover';
import {processImageFile} from '../utils/imageProcessing';
const labels={outfit:'Outfits',background:'Backgrounds',angle:'Camera angles',hair:'Hairstyles',lighting:'Lighting',pose:'Poses'};
export default function CarouselCoverBuilder({reference,photos,choices,onReference,onChoices,onBusy,onError,format}:{format:'instagram'|'tiktok';reference?:string;photos:string[];choices:CoverChoices;onReference:(v:string|undefined)=>void;onChoices:(v:CoverChoices)=>void;onBusy:(v:string)=>void;onError:(v:string)=>void}){
 const [category,setCategory]=useState<keyof CoverChoices>('outfit');const input=useRef<HTMLInputElement>(null);
 return <div className="space-y-4"><div><h5 className="font-semibold text-sm">Reference photo</h5><p className="text-xs text-slate-400 mt-1">Choose who should appear in the new image. This does not replace your current cover until you generate.</p></div>
 <CarouselPhotoPicker format={format} label="Generation reference" photos={photos} value={reference} onChange={onReference} emptyLabel="Use persona reference"/>
 <button type="button" onClick={()=>input.current?.click()} className="btn-gold-secondary px-3 py-2 text-xs">Upload reference photo</button><input ref={input} type="file" accept="image/*" className="hidden" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;onBusy('Loading reference photo…');try{onReference(await processImageFile(f));onError('');}catch(err:any){onError(err.message||'Could not load the reference photo.');}finally{onBusy('');}}}/>
 <div><h5 className="font-semibold text-sm">Style library</h5><p className="text-xs text-slate-400 mt-1">Mix optional choices. Example photos show the style; your reference supplies the person.</p></div>
 <div className="flex flex-wrap gap-2">{(Object.keys(labels) as (keyof CoverChoices)[]).map(k=><button type="button" key={k} aria-pressed={category===k} onClick={()=>setCategory(k)} className={`px-3 py-2 text-xs rounded-lg border ${category===k?'border-[#E7C477] text-[#E7C477]':'border-white/15'}`}>{labels[k]}{choices[k]?' ✓':''}</button>)}</div>
 <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><button type="button" aria-pressed={!choices[category]} onClick={()=>onChoices({...choices,[category]:undefined})} className="rounded-lg border border-white/20 text-xs p-3">Keep from reference</button>{COVER_LIBRARY[category].map(p=><button type="button" key={p.id} aria-pressed={choices[category]===p.id} onClick={()=>onChoices({...choices,[category]:p.id})} className={`rounded-lg overflow-hidden border text-left ${choices[category]===p.id?'border-[#E7C477] text-[#E7C477]':'border-white/15'}`}>{'image' in p&&<img loading="lazy" src={p.image} alt="" className="h-28 w-full object-cover"/>}<span className="block p-3 text-xs">{p.name}{choices[category]===p.id?' ✓':''}</span></button>)}</div>
 {Object.keys(choices).some(k=>choices[k as keyof CoverChoices])&&<p className="text-xs text-slate-300">Selected: {(Object.keys(choices) as (keyof CoverChoices)[]).flatMap(k=>{const p=COVER_LIBRARY[k].find(p=>p.id===choices[k]);return p?[`${labels[k]}: ${p.name}`]:[]}).join(' · ')}</p>}
 </div>;
}
