import React,{useState,useEffect,useRef} from 'react';
import {Persona} from '../types';
import {authFetch} from '../services/imageService';
import {processImageFile} from '../utils/imageProcessing';
import {CAROUSEL_FORMATS,CarouselFormat,CarouselSlide,carouselZip,validateCarousel} from '../../shared/carousel';
import {renderCarouselSlide,saveCarouselFile,CarouselTheme} from '../utils/carouselRenderer';

export default function CarouselCreator({persona}:{persona:Persona}){
 const [format,setFormat]=useState<CarouselFormat>('instagram'),[theme,setTheme]=useState<CarouselTheme>('midnight');
 const [topic,setTopic]=useState(''),[count,setCount]=useState(5),[slides,setSlides]=useState<CarouselSlide[]>([]),[caption,setCaption]=useState(''),[selected,setSelected]=useState(0);
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState(''),[previewError,setPreviewError]=useState('');
 const request=useRef(0),upload=useRef<HTMLInputElement>(null),restore=useRef<HTMLInputElement>(null);
 useEffect(()=>()=>{request.current++;},[]);
 const photos=[...new Set([persona.referenceImage,persona.avatar,...(persona.additionalReferenceImages||[]),...(persona.visualLibrary||[]).map(i=>i.url)].filter((x):x is string=>!!x))];
 const slide=slides[selected];
 useEffect(()=>{let cancelled=false;setPreview('');setPreviewError('');if(slide)renderCarouselSlide(slide,selected,slides.length,format,theme,persona.name).then(c=>{if(!cancelled)setPreview(c.toDataURL('image/jpeg',.92));}).catch(e=>{if(!cancelled)setPreviewError(e.message)});return()=>{cancelled=true};},[slide,selected,slides.length,format,theme,persona.name]);
 const update=(patch:Partial<CarouselSlide>)=>setSlides(s=>s.map((v,i)=>i===selected?{...v,...patch}:v));
 const generate=async()=>{const id=++request.current;setBusy('Generating slides…');setError('');try{
 const r=await authFetch('/api/carousel-content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({persona,topic,count,format})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Generation failed. Try again.');const valid=validateCarousel(data,count);if(id===request.current){setSlides(valid.slides.map((s,i)=>({...s,image:photos.length?photos[i%photos.length]:undefined})));setCaption(valid.caption);setSelected(0);}
 }catch(e:any){if(id===request.current)setError(e.message);}finally{if(id===request.current)setBusy('');}};
 const project=()=>({version:1,format,theme,slides,caption,topic});
 const exportAll=async()=>{setBusy('Preparing export…');setError('');try{const files:{name:string;data:Uint8Array}[]=[];for(let i=0;i<slides.length;i++){const canvas=await renderCarouselSlide(slides[i],i,slides.length,format,theme,persona.name);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Image export failed.')),'image/jpeg',.94));files.push({name:`${String(i+1).padStart(2,'0')}-slide.jpg`,data:new Uint8Array(await blob.arrayBuffer())});}
 const enc=new TextEncoder();files.push({name:'caption.txt',data:enc.encode(caption)},{name:'alt-text.txt',data:enc.encode(slides.map((s,i)=>`Slide ${i+1}: ${s.alt||s.headline+' — '+s.body}`).join('\n\n'))},{name:'carousel-project.json',data:enc.encode(JSON.stringify(project()))},{name:'posting-guide.txt',data:enc.encode(format==='instagram'?'Extract this ZIP. Upload the numbered JPGs in order as one Instagram post. Keep the same crop for every slide. Paste caption.txt, review alt text, and add music in Instagram if desired.':'Extract this ZIP. In TikTok tap +, Upload, select the numbered JPGs in order, then use photo mode. Paste caption.txt and add music in TikTok. Preview placement before posting; app controls may cover edges.')});
 saveCarouselFile(new Blob([carouselZip(files) as BlobPart],{type:'application/zip'}),`${format}-carousel.zip`);
 }catch(e:any){setError(e.message);}finally{setBusy('');}};
 const move=(delta:number)=>{const to=selected+delta;if(to<0||to>=slides.length)return;setSlides(s=>{const next=[...s];[next[selected],next[to]]=[next[to],next[selected]];return next;});setSelected(to);};
 return <fieldset disabled={!!busy} className="space-y-6 min-w-0">
  <p className="text-sm text-slate-300">Build a swipeable story: a hook, useful ideas, and a final call to action. Every slide exports at the same size.</p>
  <div className="grid gap-4 sm:grid-cols-3">
   <label className="text-xs text-slate-300">Platform<select value={format} onChange={e=>setFormat(e.target.value as CarouselFormat)} className="luxury-input mt-2 w-full p-3">{Object.entries(CAROUSEL_FORMATS).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label>
   <label className="text-xs text-slate-300">Design<select value={theme} onChange={e=>setTheme(e.target.value as CarouselTheme)} className="luxury-input mt-2 w-full p-3"><option value="midnight">Midnight editorial</option><option value="paper">Warm paper</option><option value="photo">Full photo</option></select></label>
   <label className="text-xs text-slate-300">Slides to generate<select value={count} onChange={e=>setCount(+e.target.value)} className="luxury-input mt-2 w-full p-3">{Array.from({length:8},(_,i)=>i+3).map(n=><option key={n}>{n}</option>)}</select></label>
  </div>
  <label className="block text-xs text-slate-300">Topic or source material<textarea value={topic} onChange={e=>setTopic(e.target.value)} maxLength={5000} rows={3} placeholder="e.g. Five things I wish I knew before starting strength training" className="luxury-input mt-2 p-3 w-full"/></label>
  <div className="flex gap-3 flex-wrap"><button type="button" disabled={!!busy||!topic.trim()} onClick={generate} className="btn-gold-primary px-4 py-2 text-sm disabled:opacity-50">{slides.length?'Regenerate slides':'Generate carousel'}</button><button type="button" disabled={!!busy} onClick={()=>{setSlides(Array.from({length:count},(_,i)=>({headline:i===0?'Your opening hook':i===count-1?'Your next step':`Your idea ${i}`,body:'Add a short, useful takeaway.'})));setCaption('');setSelected(0);}} className="btn-gold-secondary px-4 py-2 text-sm">Start with blank slides</button><button type="button" disabled={!!busy} onClick={()=>restore.current?.click()} className="text-xs text-slate-300 underline">Open saved project</button></div>
  <input ref={restore} type="file" accept="application/json,.json" className="hidden" onChange={async e=>{setBusy("Opening project…");try{const f=e.target.files?.[0];if(!f)return;if(f.size>25000000)throw new Error('This project is too large.');const d=JSON.parse(await f.text());if(d.version!==1||!['instagram','tiktok'].includes(d.format)||!['midnight','paper','photo'].includes(d.theme)||!Array.isArray(d.slides)||d.slides.length<2||d.slides.length>10)throw new Error('Choose a carousel-project.json exported by this tool.');const v=validateCarousel(d,d.slides.length,true);setSlides(v.slides.map((s,i)=>({...s,image:typeof d.slides[i].image==='string'&&/^(https?:|data:image\/|\/(?!\/))/.test(d.slides[i].image)?d.slides[i].image:undefined})));setCaption(v.caption);setFormat(d.format);setTheme(d.theme);setSelected(0);setTopic(String(d.topic||'').slice(0,5000));setError('');}catch(err:any){setError(err.message);}finally{setBusy('');}e.target.value='';}}/>
  {busy && <p role="status" className="text-sm text-[#E7C477]">{busy}</p>}{error && <p role="alert" className="text-sm text-red-300">{error}</p>}
  {slide && <>
   <div className="border-t border-white/10 pt-5 flex gap-2 flex-wrap" aria-label="Slides">{slides.map((s,i)=><button type="button" key={i} aria-pressed={selected===i} onClick={()=>setSelected(i)} className={`px-3 py-2 rounded-lg border text-xs ${selected===i?'border-[#E7C477] text-[#E7C477]':'border-white/15 text-slate-300'}`}>{i===0?'Cover':i===slides.length-1?'Final':`Slide ${i+1}`}</button>)}</div>
   <div className="grid md:grid-cols-2 gap-6">
    <div className="space-y-3">{preview?<img src={preview} alt={`Slide ${selected+1} preview: ${slide.headline}`} className="w-full rounded-xl border border-white/15"/>:<div className="rounded-xl bg-white/5 p-6 text-sm text-slate-400">{previewError||'Rendering slide…'}</div>}<p className="text-xs text-slate-400">{CAROUSEL_FORMATS[format].width} × {CAROUSEL_FORMATS[format].height} JPG · {format==='tiktok'?'Extra space around text for app controls.':'Portrait feed layout.'}</p></div>
    <div className="space-y-4"><label className="block text-xs text-slate-300">Headline ({slide.headline.length}/90)<textarea value={slide.headline} onChange={e=>update({headline:e.target.value})} maxLength={90} rows={2} className="luxury-input mt-2 p-3 w-full"/></label><label className="block text-xs text-slate-300">Body ({slide.body.length}/240)<textarea value={slide.body} onChange={e=>update({body:e.target.value})} maxLength={240} rows={4} className="luxury-input mt-2 p-3 w-full"/></label>
     <label className="block text-xs text-slate-300">Photo<select value={slide.image&&photos.includes(slide.image)?slide.image:slide.image?'uploaded':''} onChange={e=>{if(e.target.value!=='uploaded')update({image:e.target.value||undefined})}} className="luxury-input mt-2 w-full p-3"><option value="">Text only</option>{photos.map((url,i)=><option value={url} key={url}>Persona photo {i+1}</option>)}{slide.image&&!photos.includes(slide.image)&&<option value="uploaded">Uploaded photo</option>}</select></label>
     <button type="button" onClick={()=>upload.current?.click()} className="btn-gold-secondary px-3 py-2 text-xs">Upload photo for this slide</button><input ref={upload} type="file" accept="image/*" className="hidden" onChange={async e=>{const target=selected;setBusy("Loading photo…");try{const f=e.target.files?.[0];if(!f)return;const image=await processImageFile(f);setSlides(s=>s.map((v,i)=>i===target?{...v,image}:v));}catch(err:any){setError(err.message||'Could not load photo.');}finally{setBusy('');}e.target.value='';}}/>
     <label className="block text-xs text-slate-300">Image description / alt text<textarea value={slide.alt||''} onChange={e=>update({alt:e.target.value})} maxLength={400} rows={2} className="luxury-input mt-2 p-3 w-full"/></label>
     <div className="flex gap-3 flex-wrap"><button type="button" disabled={selected===0||!!busy} onClick={()=>move(-1)} className="text-xs text-slate-300 disabled:opacity-30">Move earlier</button><button type="button" disabled={selected===slides.length-1||!!busy} onClick={()=>move(1)} className="text-xs text-slate-300 disabled:opacity-30">Move later</button><button type="button" disabled={slides.length<=2||!!busy} onClick={()=>{setSlides(s=>s.filter((_,i)=>i!==selected));setSelected(Math.max(0,selected-1));}} className="text-xs text-red-300 disabled:opacity-30">Remove slide</button></div>
    </div>
   </div>
   <label className="block text-xs text-slate-300">Post caption<textarea value={caption} onChange={e=>setCaption(e.target.value)} maxLength={2200} rows={4} className="luxury-input mt-2 p-3 w-full"/></label>
   <div className="flex flex-wrap gap-3"><button type="button" disabled={!!busy} onClick={exportAll} className="btn-gold-primary px-5 py-3 text-sm disabled:opacity-50">Download all slides (.zip)</button><button type="button" onClick={()=>saveCarouselFile(new Blob([JSON.stringify(project())],{type:'application/json'}),'carousel-project.json')} className="btn-gold-secondary px-4 py-3 text-xs">Save editable project</button></div>
   <p className="text-xs text-slate-400">The ZIP includes numbered JPGs, caption, alt text, and your editable project. Extract it before uploading. Add music inside Instagram or TikTok and check the final crop before posting. Save your project before closing this tool.</p>
  </>}
 </fieldset>;
}
