import React, {useEffect, useState} from 'react';
export type CarouselKind='photos'|'mixed'|'slides';
const root='/demo/carousel-samples/';
const ideas=[['Photo diary','Everyday moments'],['Day in my life','A day from start to finish'],['Outfit lookbook','Looks and styling notes'],['Travel / city guide','Places to visit'],['Favorites / top five','Personal recommendations'],['Moodboard / scrapbook','Visual inspiration'],['Before & after','A transformation or reveal'],['How-to / tutorial','One practical step per slide'],['Tips / checklist','Easy-to-save advice'],['Personal story','A beginning, middle and end'],['Lessons learned','Experiences and takeaways'],['Comparison / this or that','Compare your options'],['Behind the scenes','How it came together'],['Food / weekly meals','A visual food diary'],['Routine / Sunday reset','Small steps through a routine'],['Wishlist / products','A curated collection'],['Quotes / opinions','A point of view'],['Meme / relatable story','A lighthearted sequence']];
export default function CarouselStart({onStart}:{onStart:(kind:CarouselKind,idea:string)=>void}) {
 const [kind,setKind]=useState<CarouselKind>('photos'),[idea,setIdea]=useState('Photo diary'),[sample,setSample]=useState(false),[index,setIndex]=useState(0),[playing,setPlaying]=useState(false);
 useEffect(()=>{if(!playing||!sample)return;const id=window.setInterval(()=>{if(!document.hidden)setIndex(i=>(i+1)%5)},2400);return()=>clearInterval(id)},[playing,sample]);
 return <section className="space-y-6">
 {!sample?<><div><h3 className="text-xl font-semibold">What kind of carousel do you want?</h3><p className="text-sm text-slate-400 mt-2">Start with a format. You can add photos, generate images, or change the style later.</p></div>
 <div className="grid grid-cols-3 gap-2 sm:gap-4">{(['photos','mixed','slides'] as const).map(k=><button type="button" key={k} aria-pressed={kind===k} onClick={()=>setKind(k)} className={`rounded-xl p-2 sm:p-3 text-left border transition-colors ${kind===k?'border-[#E7C477]':'border-white/15 hover:border-white/40'}`}><div className={`relative h-32 sm:h-44 overflow-hidden rounded-lg ${k==='slides'?'bg-[#eee6d7] text-[#242326]':'bg-black'}`}>{k!=='slides'&&<img src={root+'slide-1.png'} alt="" className={`w-full h-full object-cover ${k==='mixed'?'opacity-50':''}`}/>}{k!=='photos'&&<strong className="absolute left-3 right-2 bottom-4 text-base sm:text-xl leading-tight">{k==='slides'?'5 things I learned':'Small moments, a good day.'}</strong>}</div><strong className="block mt-3 text-sm sm:text-base">{k==='photos'?'Photos only':k==='mixed'?'Photos + text':'Text slides'}</strong><span className="block mt-2 text-xs text-slate-400">{k==='photos'?'Let the pictures tell the story. No text required.':k==='mixed'?'Add titles, notes, or a story to photos.':'Share tips, lists, or a step-by-step guide.'}</span></button>)}</div>
 <details><summary className="cursor-pointer text-sm font-semibold py-2">Pick a story idea · {idea}</summary><p className="text-xs text-slate-400 my-3">Optional inspiration. These are common creator formats, not a live trend ranking.</p><div className="grid grid-cols-3 sm:grid-cols-4 lg:grid-cols-6 gap-3">{ideas.map(([title,description],i)=><button type="button" key={title} aria-pressed={idea===title} onClick={()=>setIdea(title)} className={`rounded-xl overflow-hidden border text-left ${idea===title?'border-[#E7C477]':'border-white/15'}`}><div className="relative h-24"><img loading="lazy" src={root+`slide-${i%5+1}.png`} alt="" className="w-full h-full object-cover opacity-40"/><strong className="absolute bottom-2 left-2 right-2 text-xs">{title}</strong></div><span className="block p-2 text-[11px] text-slate-400">{description}</span></button>)}</div></details>
 <div className="flex flex-wrap items-center gap-3"><button type="button" className="btn-gold-primary px-5 py-3 text-sm" onClick={()=>onStart(kind,idea)}>Start my carousel</button><button type="button" className="btn-gold-secondary px-4 py-3 text-sm" onClick={()=>setSample(true)}>See a five-slide sample</button></div></>:<>
 <button type="button" onClick={()=>{setSample(false);setPlaying(false)}} className="text-sm text-slate-400">‹ Back to carousel types</button>
 <div><h3 className="text-lg font-semibold">One reference. Five moments.</h3><p className="text-xs text-slate-400 mt-2">AI-generated café diary featuring Rawan. This sample stays separate from your own carousel.</p></div>
 <div className="grid grid-cols-[.7fr_1fr] gap-4 max-w-xl mx-auto"><figure><figcaption className="text-xs text-slate-400 mb-2">Persona reference</figcaption><img src={root+'reference.jpg'} alt="Rawan reference for the sample" className="w-full aspect-[4/5] object-cover rounded-xl"/></figure><figure><figcaption className="text-xs text-slate-400 mb-2">Generated sample · {index+1} of 5</figcaption><img src={root+`slide-${index+1}.png`} alt={`Rawan café diary sample, slide ${index+1}`} className="w-full aspect-[4/5] object-cover rounded-xl"/></figure></div>
 <div className="flex justify-center items-center gap-4"><button type="button" aria-label="Previous sample slide" className="btn-gold-secondary px-4 py-3" onClick={()=>{setPlaying(false);setIndex(i=>(i+4)%5)}}>‹</button><button type="button" className="btn-gold-secondary px-4 py-3 text-sm" onClick={()=>setPlaying(p=>!p)}>{playing?'Pause':'Play preview'}</button><button type="button" aria-label="Next sample slide" className="btn-gold-secondary px-4 py-3" onClick={()=>{setPlaying(false);setIndex(i=>(i+1)%5)}}>›</button></div><button type="button" className="btn-gold-primary px-5 py-3 text-sm" onClick={()=>onStart(kind,idea)}>Start with my persona</button>
 </>}
 </section>
}
