import React,{useState,useEffect,useRef} from 'react';
import {Persona} from '../types';
import {authFetch} from '../services/imageService';
import {processImageFile} from '../utils/imageProcessing';
import {CAROUSEL_FORMATS,CarouselFormat,CarouselSlide,carouselZip,validateCarousel,normalizeSlideDesign,CarouselLayout,packCarouselImages,unpackCarouselImages} from '../../shared/carousel';
import {renderCarouselSlide,saveCarouselFile,CarouselTheme} from '../utils/carouselRenderer';

import CarouselDesignControls,{LAYOUTS} from './CarouselDesignControls';

function DesignPreview({theme,image,layout='editorial'}:{theme:CarouselTheme;image?:string;layout?:CarouselLayout}) {
 const [src,setSrc]=useState('');
 useEffect(()=>{let cancelled=false;renderCarouselSlide({headline:'Your story starts here',body:'One idea. A clear next step.',image,layout},0,5,'instagram',theme,'YOUR PERSONA').then(c=>{if(!cancelled)setSrc(c.toDataURL('image/jpeg',.8));}).catch(()=>{if(!cancelled)setSrc('');});return()=>{cancelled=true};},[theme,image,layout]);
 return src?<img src={src} alt="" className="w-full h-32 sm:h-48 object-contain rounded-lg"/>:<div className="h-32 sm:h-48 rounded-lg bg-white/10"/>;
}

export default function CarouselCreator({persona}:{persona:Persona}){
 const [format,setFormat]=useState<CarouselFormat>('instagram'),[theme,setTheme]=useState<CarouselTheme>('midnight');
 const [topic,setTopic]=useState(''),[count,setCount]=useState(5),[slides,setSlides]=useState<CarouselSlide[]>([]),[caption,setCaption]=useState(''),[selected,setSelected]=useState(0);
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState(''),[previewError,setPreviewError]=useState('');
 const [layout,setLayout]=useState<CarouselLayout>('editorial'),[safeAreas,setSafeAreas]=useState(false),[referenceAdvice,setReferenceAdvice]=useState('');
 const referenceUpload=useRef<HTMLInputElement>(null);
 const [uploadedPhotos,setUploadedPhotos]=useState<string[]>([]);
 const sourceUpload=useRef<HTMLInputElement>(null);
 const request=useRef(0),upload=useRef<HTMLInputElement>(null),restore=useRef<HTMLInputElement>(null);
 useEffect(()=>()=>{request.current++;},[]);
 const photos=[...new Set([...uploadedPhotos,persona.referenceImage,persona.avatar,...(persona.additionalReferenceImages||[]),...(persona.visualLibrary||[]).map(i=>i.url)].filter((x):x is string=>!!x))];
 const startingPhotos=uploadedPhotos.length?uploadedPhotos:photos;
 const slide=slides[selected];
 useEffect(()=>{let cancelled=false;setPreview('');setPreviewError('');if(slide)renderCarouselSlide(slide,selected,slides.length,format,theme,persona.name).then(c=>{if(!cancelled)setPreview(c.toDataURL('image/jpeg',.92));}).catch(e=>{if(!cancelled)setPreviewError(e.message)});return()=>{cancelled=true};},[slide,selected,slides.length,format,theme,persona.name]);
 const update=(patch:Partial<CarouselSlide>)=>setSlides(s=>s.map((v,i)=>i===selected?{...v,...patch}:v));
 const generate=async()=>{const id=++request.current;setBusy('Generating slides…');setError('');try{
 const r=await authFetch('/api/carousel-content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({persona,topic,count,format,layout})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Generation failed. Try again.');const valid=validateCarousel(data,count);if(id===request.current){setSlides(valid.slides.map((s,i)=>({...s,layout,image:startingPhotos.length?startingPhotos[layout==='panorama'?0:i%startingPhotos.length]:undefined,secondImage:startingPhotos[(i+1)%startingPhotos.length]})));setCaption(valid.caption);setSelected(0);}
 }catch(e:any){if(id===request.current)setError(e.message);}finally{if(id===request.current)setBusy('');}};
 const project=()=>({version:2,format,theme,layout,...packCarouselImages(slides),caption,topic});
 const exportAll=async()=>{setBusy('Preparing export…');setError('');try{const files:{name:string;data:Uint8Array}[]=[];for(let i=0;i<slides.length;i++){const canvas=await renderCarouselSlide(slides[i],i,slides.length,format,theme,persona.name);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Image export failed.')),'image/jpeg',.94));files.push({name:`${String(i+1).padStart(2,'0')}-slide.jpg`,data:new Uint8Array(await blob.arrayBuffer())});}
 const enc=new TextEncoder();files.push({name:'caption.txt',data:enc.encode(caption)},{name:'alt-text.txt',data:enc.encode(slides.map((s,i)=>`Slide ${i+1}: ${s.alt||s.headline+' — '+s.body}`).join('\n\n'))},{name:'carousel-project.json',data:enc.encode(JSON.stringify(project()))},{name:'posting-guide.txt',data:enc.encode(format==='instagram'?'Extract this ZIP. Upload the numbered JPGs in order as one Instagram post. Keep the same crop for every slide. Paste caption.txt, review alt text, and add music in Instagram if desired.':'Extract this ZIP. In TikTok tap +, Upload, select the numbered JPGs in order, then use photo mode. Paste caption.txt and add music in TikTok. Preview placement before posting; app controls may cover edges.')});
 saveCarouselFile(new Blob([carouselZip(files) as BlobPart],{type:'application/zip'}),`${format}-carousel.zip`);
 }catch(e:any){setError(e.message);}finally{setBusy('');}};
 const move=(delta:number)=>{const to=selected+delta;if(to<0||to>=slides.length)return;setSlides(s=>{const next=[...s];[next[selected],next[to]]=[next[to],next[selected]];return next;});setSelected(to);};
 return <fieldset disabled={!!busy} className="space-y-6 min-w-0">
  <p className="text-sm text-slate-300">Build a swipeable story: a hook, useful ideas, and a final call to action. Every slide exports at the same size.</p>
  <div className="grid gap-4 sm:grid-cols-2">
   <label className="text-xs text-slate-300">Platform<select value={format} onChange={e=>setFormat(e.target.value as CarouselFormat)} className="luxury-input mt-2 w-full p-3">{Object.entries(CAROUSEL_FORMATS).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label>
   <label className="text-xs text-slate-300">Slides to generate<select value={count} onChange={e=>setCount(+e.target.value)} className="luxury-input mt-2 w-full p-3">{Array.from({length:8},(_,i)=>i+3).map(n=><option key={n}>{n}</option>)}</select></label>
  </div>
  <section className="rounded-xl border border-white/15 p-4 space-y-3" aria-label="Carousel photos">
   <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold text-white">Add your photos</h3><p className="text-xs text-slate-400 mt-1">Upload up to 10 photos before creating slides. They’ll be used in order, repeating if needed.</p></div><button type="button" onClick={()=>sourceUpload.current?.click()} className="btn-gold-primary px-4 py-2 text-sm">Upload photos</button></div>
   <input ref={sourceUpload} type="file" accept="image/*" multiple className="hidden" aria-label="Upload carousel photos" onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;setBusy('Loading photos…');setError('');try{if(files.length+uploadedPhotos.length>10)throw new Error('You can add up to 10 photos. Remove a photo before adding more.');const images:string[]=[];for(const f of files)images.push(await processImageFile(f));setUploadedPhotos(p=>[...p,...images]);}catch(err:any){setError(err.message||'Could not load the photos.');}finally{setBusy('');}}}/>
   {uploadedPhotos.length>0?<><div className="flex gap-3 overflow-x-auto">{uploadedPhotos.map((src,i)=><div key={i} className="shrink-0 w-24"><img src={src} alt={`Uploaded photo ${i+1}`} className="w-24 h-24 rounded-lg object-cover"/><button type="button" onClick={()=>setUploadedPhotos(p=>p.filter((_,n)=>n!==i))} className="text-xs text-slate-300 mt-2">Remove photo {i+1}</button></div>)}</div>{slides.length>0&&<button type="button" onClick={()=>setSlides(s=>s.map((v,i)=>({...v,image:uploadedPhotos[i%uploadedPhotos.length]})))} className="btn-gold-secondary px-3 py-2 text-xs">Apply uploaded photos to existing slides</button>}</>:<p className="text-xs text-slate-400">Without uploads, generated slides use your saved persona photos. You can change each slide’s photo later.</p>}
  </section>
  <section aria-label="Slide design" className="space-y-3"><h3 className="text-sm font-semibold text-white">Choose a design</h3><div className="grid grid-cols-3 gap-2 sm:gap-4">{([
   {id:'midnight',name:'Dark background',description:'Photo above cream text on a dark background.'},
   {id:'paper',name:'Light background',description:'Photo above dark text on a warm light background.'},
   {id:'photo',name:'Photo background',description:'Full-slide photo with text over a dark overlay.'},
  ] as const).map(d=><button key={d.id} type="button" aria-pressed={theme===d.id} onClick={()=>setTheme(d.id)} className={`min-w-0 rounded-xl border p-2 sm:p-3 text-left ${theme===d.id?'border-[#E7C477] bg-[#E7C477]/10':'border-white/15'}`}><DesignPreview theme={d.id} image={startingPhotos[0] || '/examples/showcase_parisian_chic.png'}/><span className="block text-xs sm:text-sm font-semibold text-white mt-3">{d.name}{theme===d.id?' ✓':''}</span><span className="block text-[11px] sm:text-xs text-slate-400 mt-1">{d.description}</span></button>)}</div></section>
  <section className="space-y-3" aria-label="Carousel layouts"><h3 className="font-semibold">Choose your layout</h3><p className="text-xs text-slate-400">Use these for photo dumps, lookbooks, story reveals, comparisons, rankings, or useful mini guides.</p><div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{LAYOUTS.map(l=><button type="button" key={l.id} aria-pressed={layout===l.id} onClick={()=>{setLayout(l.id);}} className={`rounded-xl border p-3 text-left ${layout===l.id?'border-[#E7C477] bg-[#E7C477]/10':'border-white/15'}`}><DesignPreview layout={l.id} theme={theme} image={startingPhotos[0]||'/examples/showcase_parisian_chic.png'}/><span className="block text-sm font-semibold mt-2">{l.name}</span><span className="block text-xs text-slate-400 mt-1">{l.description}</span></button>)}</div>{slides.length>0&&<button type="button" className="btn-gold-secondary px-3 py-2 text-xs" onClick={()=>setSlides(s=>s.map((v,i)=>({...v,layout,image:layout==='panorama'?s[0].image:v.image,...(layout==='panorama'?{cropX:s[0].cropX,cropY:s[0].cropY,zoom:s[0].zoom}:{}),secondImage:v.secondImage||startingPhotos[(i+1)%startingPhotos.length]})))}>Apply selected layout to existing slides</button>}</section>
  <section className="border border-white/15 rounded-xl p-4 space-y-3"><h3 className="font-semibold">Inspired by a carousel?</h3><p className="text-xs text-slate-400">Upload a screenshot. Your existing Gemini connection will suggest a layout, photo treatment, and writing approach. Your photos and text stay your own. Uses your existing API credits.</p><button type="button" onClick={()=>referenceUpload.current?.click()} className="btn-gold-secondary px-3 py-2 text-xs">Analyze a reference screenshot</button><input ref={referenceUpload} type="file" accept="image/*" className="hidden" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;setBusy('Analyzing reference…');setError('');try{const image=await processImageFile(f);const r=await authFetch('/api/carousel-reference',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not analyze reference.');setReferenceAdvice(d.advice);setLayout(normalizeSlideDesign(d).layout||'editorial');}catch(err:any){setError(err.message);}finally{setBusy('');}}}/>{referenceAdvice&&<p className="text-sm text-slate-300 whitespace-pre-line">{referenceAdvice}</p>}</section>
  <label className="block text-xs text-slate-300">Topic or source material<textarea value={topic} onChange={e=>setTopic(e.target.value)} maxLength={5000} rows={3} placeholder="e.g. Five things I wish I knew before starting strength training" className="luxury-input mt-2 p-3 w-full"/></label>
  <div className="flex gap-3 flex-wrap"><button type="button" disabled={!!busy||!topic.trim()} onClick={generate} className="btn-gold-primary px-4 py-2 text-sm disabled:opacity-50">{slides.length?'Regenerate slides':'Generate carousel'}</button><button type="button" disabled={!!busy} onClick={()=>{setSlides(Array.from({length:count},(_,i)=>({headline:i===0?'Your opening hook':i===count-1?'Your next step':`Your idea ${i}`,body:'Add a short, useful takeaway.',layout,image:startingPhotos.length?startingPhotos[layout==='panorama'?0:i%startingPhotos.length]:undefined,secondImage:startingPhotos[(i+1)%startingPhotos.length]})));setCaption('');setSelected(0);}} className="btn-gold-secondary px-4 py-2 text-sm">Start with blank slides</button><button type="button" disabled={!!busy} onClick={()=>restore.current?.click()} className="text-xs text-slate-300 underline">Open saved project</button></div>
  <input ref={restore} type="file" accept="application/json,.json" className="hidden" onChange={async e=>{setBusy("Opening project…");try{const f=e.target.files?.[0];if(!f)return;if(f.size>100000000)throw new Error('This project is too large.');const d=JSON.parse(await f.text());if(![1,2].includes(d.version)||!['instagram','tiktok'].includes(d.format)||!['midnight','paper','photo'].includes(d.theme)||!Array.isArray(d.slides)||d.slides.length<2||d.slides.length>10)throw new Error('Choose a carousel-project.json exported by this tool.');const v=validateCarousel(d,d.slides.length,true);setSlides(v.slides.map((s,i)=>({...s,...unpackCarouselImages(d.slides[i],d.assets)})));setLayout(normalizeSlideDesign({layout:d.layout}).layout||'editorial');setCaption(v.caption);setFormat(d.format);setTheme(d.theme);setSelected(0);setTopic(String(d.topic||'').slice(0,5000));setError('');}catch(err:any){setError(err.message);}finally{setBusy('');}e.target.value='';}}/>
  {busy && <p role="status" className="text-sm text-[#E7C477]">{busy}</p>}{error && <p role="alert" className="text-sm text-red-300">{error}</p>}
  {slide && <>
   <div className="border-t border-white/10 pt-5 flex gap-2 flex-wrap" aria-label="Slides">{slides.map((s,i)=><button type="button" key={i} aria-pressed={selected===i} onClick={()=>setSelected(i)} className={`px-3 py-2 rounded-lg border text-xs ${selected===i?'border-[#E7C477] text-[#E7C477]':'border-white/15 text-slate-300'}`}>{i===0?'Cover':i===slides.length-1?'Final':`Slide ${i+1}`}</button>)}</div>
   <div className="grid md:grid-cols-2 gap-6">
    <div className="space-y-3"><label className="flex gap-2 text-xs"><input type="checkbox" checked={safeAreas} onChange={e=>setSafeAreas(e.target.checked)}/>Show approximate safe area (preview only)</label><div className="relative">{safeAreas&&preview&&<div className="pointer-events-none absolute border-2 border-dashed border-cyan-300 z-10" style={{left:"7.4%",right:format==='tiktok'?"18.5%":"7.4%",top:format==='tiktok'?"9.4%":"6.3%",bottom:format==='tiktok'?"16.1%":"7.4%"}}/>}{preview?<img src={preview} alt={`Slide ${selected+1} preview: ${slide.headline}`} className="w-full rounded-xl border border-white/15"/>:<div className="rounded-xl bg-white/5 p-6 text-sm text-slate-400">{previewError||'Rendering slide…'}</div>}</div><p className="text-xs text-slate-400">{CAROUSEL_FORMATS[format].width} × {CAROUSEL_FORMATS[format].height} JPG · {format==='tiktok'?'Extra space around text for app controls.':'Portrait feed layout.'}</p></div>
    <div className="space-y-4"><label className="block text-xs text-slate-300">Headline ({slide.headline.length}/90)<textarea value={slide.headline} onChange={e=>update({headline:e.target.value})} maxLength={90} rows={2} className="luxury-input mt-2 p-3 w-full"/></label><label className="block text-xs text-slate-300">Body ({slide.body.length}/240)<textarea value={slide.body} onChange={e=>update({body:e.target.value})} maxLength={240} rows={4} className="luxury-input mt-2 p-3 w-full"/></label>
     <label className="block text-xs text-slate-300">Photo<select value={slide.image&&photos.includes(slide.image)?slide.image:slide.image?'uploaded':''} onChange={e=>{if(e.target.value!=='uploaded')update({image:e.target.value||undefined})}} className="luxury-input mt-2 w-full p-3"><option value="">Text only</option>{photos.map((url,i)=><option value={url} key={url}>Photo {i+1}</option>)}{slide.image&&!photos.includes(slide.image)&&<option value="uploaded">Uploaded photo</option>}</select></label>
     <button type="button" onClick={()=>upload.current?.click()} className="btn-gold-secondary px-3 py-2 text-xs">Upload photo for this slide</button><input ref={upload} type="file" accept="image/*" className="hidden" onChange={async e=>{const target=selected;setBusy("Loading photo…");try{const f=e.target.files?.[0];if(!f)return;const image=await processImageFile(f);setSlides(s=>s.map((v,i)=>i===target?{...v,image}:v));}catch(err:any){setError(err.message||'Could not load photo.');}finally{setBusy('');}e.target.value='';}}/>
     <CarouselDesignControls slide={slide} photos={photos} onChange={update} onPanorama={()=>setSlides(s=>s.map(v=>({...v,layout:'panorama',image:slide.image,cropX:slide.cropX,cropY:slide.cropY,zoom:slide.zoom})))}/>
     <label className="block text-xs text-slate-300">Image description / alt text<textarea value={slide.alt||''} onChange={e=>update({alt:e.target.value})} maxLength={400} rows={2} className="luxury-input mt-2 p-3 w-full"/></label>
     <div className="flex gap-3 flex-wrap"><button type="button" disabled={selected===0||!!busy} onClick={()=>move(-1)} className="text-xs text-slate-300 disabled:opacity-30">Move earlier</button><button type="button" disabled={selected===slides.length-1||!!busy} onClick={()=>move(1)} className="text-xs text-slate-300 disabled:opacity-30">Move later</button><button type="button" disabled={slides.length<=2||!!busy} onClick={()=>{setSlides(s=>s.filter((_,i)=>i!==selected));setSelected(Math.max(0,selected-1));}} className="text-xs text-red-300 disabled:opacity-30">Remove slide</button></div>
    </div>
   </div>
   <label className="block text-xs text-slate-300">Post caption<textarea value={caption} onChange={e=>setCaption(e.target.value)} maxLength={2200} rows={4} className="luxury-input mt-2 p-3 w-full"/></label>
   <div className="flex flex-wrap gap-3"><button type="button" disabled={!!busy} onClick={exportAll} className="btn-gold-primary px-5 py-3 text-sm disabled:opacity-50">Download all slides (.zip)</button><button type="button" onClick={()=>saveCarouselFile(new Blob([JSON.stringify(project())],{type:'application/json'}),'carousel-project.json')} className="btn-gold-secondary px-4 py-3 text-xs">Save editable project</button></div>
   <p className="text-xs text-slate-400">The ZIP includes numbered JPGs, caption, alt text, and your editable project. Extract it before uploading. Add music inside Instagram or TikTok and check the final crop before posting. Save your project before closing this tool.</p>
  </>}
 </fieldset>;
}
