import { mergeWordRecording } from '../utils/wordRecording';
import { playDialectPreview, requestDialectPreview } from '../utils/dialectPreview';
import { useEffect, useRef, useState } from 'react';
import { Mic, Square, Play, Trash2, BookOpen } from 'lucide-react';
import { getAuthHeaders } from '../services/apiService';
import { accountLocalStorage } from '../utils/accountStorage';
import { DIALECT_PROFILES, unapprovedDialectCandidates, type DialectProfileId, type DialectProfile, type DialectRule } from '../../shared/dialectTeaching';
const names={'jordanian-syrian':'Jordanian–Syrian mix',jordanian:'Jordanian',syrian:'Syrian'};
async function request(id:string,suffix='',options:RequestInit={}) {
 const response=await fetch('/api/dialect-teaching/'+id+suffix,{...options,signal:options.signal?AbortSignal.any([options.signal,AbortSignal.timeout(75000)]):AbortSignal.timeout(75000),headers:{'Content-Type':'application/json',...await getAuthHeaders()}});
 const data=await response.json();if(!response.ok)throw Object.assign(new Error(data.error||'Dialect request failed.'),{status:response.status});return data;
}
export function DialectTeaching({onPreview,onUseDialect,disabled=false}:{onPreview?:(text:string)=>Promise<string>;onUseDialect?:(id:DialectProfileId)=>void;disabled?:boolean}) {
 const [id,setId]=useState<DialectProfileId>('jordanian-syrian'),[profile,setProfile]=useState<DialectProfile>({id:'jordanian-syrian',revision:0,rules:[]}),[candidates,setCandidates]=useState<DialectRule[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[pending,setPending]=useState(''),[file,setFile]=useState<File|null>(null),[audioUrl,setAudioUrl]=useState(''),[loaded,setLoaded]=useState(false),[previewUrl,setPreviewUrl]=useState(''),[references,setReferences]=useState<Array<{id:string;name:string;status:string}>>([]);
 const [previewRuleId,setPreviewRuleId]=useState(''),[previewError,setPreviewError]=useState('');
 const [reviewResult,setReviewResult]=useState<{id:string;name:string;status:string}|null>(null);
 const approvedDetails=useRef<HTMLDetailsElement|null>(null);
 const [wordTarget,setWordTarget]=useState<DialectRule|null>(null);
 const [manual,setManual]=useState<DialectRule>({id:'',kind:'wording',word:'',replacement:'',example:'',recordingId:''});
 const [undo,setUndo]=useState<DialectRule|null>(null);
 const scope=useRef<AbortController|null>(null),lock=useRef(false),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),playback=useRef<HTMLAudioElement|null>(null),previewPlayback=useRef<HTMLAudioElement|null>(null);
 useEffect(()=>{const controller=new AbortController();scope.current=controller;setCandidates([]);setReviewResult(null);setPreviewUrl('');setPreviewRuleId('');setPreviewError('');setReferences([]);setError('');setLoaded(false);setProfile({id,revision:0,rules:[]});setUndo(null);setFile(null);setWordTarget(null);setPending(accountLocalStorage.getItem('dialect-pending:'+id)||'');void request(id,'',{signal:controller.signal}).then(data=>{if(!controller.signal.aborted){setProfile(data);setLoaded(true);void request(id,'/recordings',{signal:controller.signal}).then(rows=>{if(!controller.signal.aborted)setReferences(rows.recordings);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>{controller.abort();playback.current?.pause();previewPlayback.current?.pause();if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());};},[id]);
 useEffect(()=>{if(!file){setAudioUrl('');return;}const url=URL.createObjectURL(file);setAudioUrl(url);return()=>URL.revokeObjectURL(url);},[file]);
 async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await action();}catch(e){if(!scope.current?.signal.aborted)setError(e instanceof Error?e.message:'Request failed.');}finally{lock.current=false;setBusy(false);}}
 async function analyze(){if(!file||lock.current||pending)return;const controller=scope.current!;const operationId=crypto.randomUUID();setPending(operationId);accountLocalStorage.setItem('dialect-pending:'+id,operationId);await run(async()=>{
  if(file.size>2*1024*1024){setPending('');accountLocalStorage.removeItem('dialect-pending:'+id);throw new Error('Use a recording under 2 MB. Short recordings work best.');}
  const audio=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('Could not read audio.'));r.readAsDataURL(file);});
  let data;try{data=await request(id,'/recordings',{method:'POST',body:JSON.stringify({audio,name:file.name,operationId,...(wordTarget?{targetWord:wordTarget.word}:{})}),signal:controller.signal});}catch(e){if([400,401,403,413].includes((e as any).status)&&!controller.signal.aborted){setPending('');accountLocalStorage.removeItem('dialect-pending:'+id);}throw e;}if(controller.signal.aborted)return;if(wordTarget&&data.status==='ready'){const correction=data.candidates?.[0];if(!correction){setPending('');accountLocalStorage.removeItem('dialect-pending:'+id);throw new Error('Could not identify a confident pronunciation for this word. Record it again, clearly and without background sound.');}if(wordTarget.recordingId&&candidates.some(c=>c.id===wordTarget.id)){await request(id,'/recordings/'+wordTarget.recordingId+'/review',{method:'PUT',body:JSON.stringify({candidateIds:[wordTarget.id]}),signal:controller.signal});if(controller.signal.aborted)return;}setCandidates(rows=>mergeWordRecording(rows,wordTarget.kind==='pronunciation'?wordTarget.id:'',correction));setWordTarget(correction);setFile(null);}else setCandidates(data.candidates||[]);setReferences(rows=>[{id:data.id,name:file.name,status:data.status},...rows.filter(r=>r.id!==data.id)]);if(data.status==='ready'){setPending('');accountLocalStorage.removeItem('dialect-pending:'+id);}else throw new Error(data.error||'Analysis is still unresolved. Check status.');
 });}
 async function check(){const controller=scope.current!;await run(async()=>{let data;try{data=await request(id,'/recordings/'+pending,{signal:controller.signal});}catch(e){if((e as any).status===404&&!controller.signal.aborted){setPending('');accountLocalStorage.removeItem('dialect-pending:'+id);}throw e;}if(controller.signal.aborted)return;if(wordTarget&&data.candidates?.[0]){setCandidates(rows=>mergeWordRecording(rows,wordTarget.kind==='pronunciation'?wordTarget.id:'',data.candidates[0]));setWordTarget(data.candidates[0]);setFile(null);}else if(!wordTarget)setCandidates(data.candidates||[]);if(data.status==='ready'){setPending('');accountLocalStorage.removeItem('dialect-pending:'+id);if(wordTarget&&!data.candidates?.length)throw new Error('Could not identify a confident pronunciation. Record this word again.');}else throw new Error(data.error||'Analysis is not finished. No duplicate request was sent.');});}
 async function save(rule?:DialectRule,removeId?:string,replace=false){const controller=scope.current!;await run(async()=>{const previous=profile.rules.find(r=>removeId?r.id===removeId:r.kind===rule?.kind&&r.word.toLowerCase()===rule.word.toLowerCase());if(rule&&previous&&previous.replacement!==rule.replacement&&!replace&&!window.confirm(`Replace the existing correction for “${rule.word}”?`))return;
  const data=await request(id,'',{method:'PUT',body:JSON.stringify({revision:profile.revision,rule,removeId,replace:true}),signal:controller.signal});if(controller.signal.aborted)return;setProfile(data);setUndo(removeId?previous||null:null);if(rule)setCandidates(rows=>rows.filter(r=>r.id!==rule.id));if(rule===manual)setManual({...manual,word:'',replacement:'',example:''});
 });}
 async function start(target?:DialectRule){if(lock.current||disabled||recorder.current?.state==='recording')return;lock.current=true;const controller=scope.current!;setBusy(true);setError('');setFile(null);setWordTarget(target||null);playback.current?.pause();previewPlayback.current?.pause();setPreviewUrl('');try{const captured=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,channelCount:1}});if(controller.signal.aborted){captured.getTracks().forEach(t=>t.stop());return;}stream.current=captured;const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(m=>MediaRecorder.isTypeSupported(m));const r=new MediaRecorder(captured,mime?{mimeType:mime,audioBitsPerSecond:48000}:{audioBitsPerSecond:48000});recorder.current=r;const chunks:BlobPart[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};r.onstop=()=>{captured.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);if(!controller.signal.aborted){setFile(new File(chunks,(target?'Word pronunciation':'Dialect reference')+'.'+(r.mimeType.includes('mp4')?'m4a':r.mimeType.includes('ogg')?'ogg':'webm'),{type:r.mimeType}));setRecording(false);}};r.start();setRecording(true);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop();},target?15000:120000);}catch{if(!controller.signal.aborted)setError('Microphone unavailable. Allow access or upload an audio file.');}finally{lock.current=false;if(!controller.signal.aborted)setBusy(false);}}
 async function preview(rule:DialectRule){if(lock.current||!onPreview)return;playback.current?.pause();previewPlayback.current?.pause();setPreviewRuleId(rule.id);setPreviewUrl('');setPreviewError('');const controller=scope.current!;await run(async()=>{try{const url=await requestDialectPreview(onPreview,rule.kind==='pronunciation'?rule.replacement:rule.example||rule.replacement);if(!controller.signal.aborted)setPreviewUrl(url);}catch(e){if(!controller.signal.aborted)setPreviewError(e instanceof Error?e.message:'Could not generate the preview. Try Listen again.');}});}
 useEffect(()=>{if(previewUrl&&previewPlayback.current)void playDialectPreview(previewPlayback.current,message=>{if(!scope.current?.signal.aborted)setPreviewError(message);});},[previewUrl]);
 const recordButton=(rule:DialectRule)=><button type="button" aria-label={recording&&wordTarget?.id===rule.id?`Stop recording ${rule.word}`:`Record pronunciation for ${rule.word}`} title="Say this word again" disabled={busy||disabled||!!pending||(recording&&wordTarget?.id!==rule.id)} onClick={()=>recording?recorder.current?.stop():void start(rule.kind==='wording'?{...rule,word:rule.replacement}:rule)} className="flex min-h-11 items-center gap-1 text-[#E7C477]">{recording&&wordTarget?.id===rule.id?<Square size={15}/>:<Mic size={15}/>} {recording&&wordTarget?.id===rule.id?'Stop':'Say again'}</button>;
 const wordRecorder=(ruleId:string)=>wordTarget?.id===ruleId&&(recording||file)?<div className="space-y-2 rounded-lg border border-white/10 p-2" aria-live="polite">{recording?<p className="text-xs text-[#E7C477]">Say “{wordTarget.word}” naturally, then press Stop. Recording stops after 15 seconds.</p>:file?<><p className="text-xs text-zinc-400">Listen to your recording, then analyze it. The correction stays a draft until you approve it.</p><audio ref={playback} controls src={audioUrl} aria-label="Your word recording" className="w-full"/><button type="button" disabled={busy||!!pending} onClick={()=>void analyze()} className="min-h-11 rounded-lg bg-[#E7C477] px-3 text-sm text-black">{busy?'Analyzing pronunciation…':'Analyze pronunciation'}</button></>:null}</div>:null;
 const previewPlayer=(ruleId:string)=>previewRuleId===ruleId?<div aria-live="polite" className="space-y-2">{busy&&<p role="status" className="text-xs text-[#E7C477]">Preparing this voice sample…</p>}{previewError&&<p role="alert" className="text-sm text-amber-200">{previewError}</p>}{previewUrl&&<audio ref={previewPlayback} controls src={previewUrl} className="w-full" aria-label="Persona dialect preview" onError={()=>setPreviewError('This audio could not be played. Try Listen again or choose another voice engine.')} />}</div>:null;
 return <details open className="rounded-xl border border-[#E7C477]/25 p-3"><summary className="cursor-pointer text-sm font-medium text-[#E7C477]"><BookOpen size={15} className="mr-2 inline"/>Teach dialect</summary><div className="mt-3 space-y-3">
 <p className="text-xs leading-relaxed text-zinc-400">Keep each persona’s voice. Add recordings over time, listen to suggested corrections, then approve them. Rules apply to personas using this dialect; reconnect direct provider calls after changes. This guides speech, rather than retraining the voice model.</p>
 <label className="block text-sm">Shared dialect profile<select aria-label="Teaching dialect profile" value={id} disabled={busy||recording} onChange={e=>setId(e.target.value as DialectProfileId)} className="mt-1 min-h-11 w-full rounded-lg bg-[#151515] px-3">{DIALECT_PROFILES.map(v=><option key={v} value={v}>{names[v]}</option>)}</select></label>{onUseDialect&&<button type="button" disabled={busy||recording||disabled} onClick={()=>onUseDialect(id)} className="min-h-11 text-sm text-[#E7C477]">Use this dialect for this persona’s calls</button>}
 <div className="flex flex-wrap items-center gap-2"><label className="min-h-11 cursor-pointer rounded-lg border border-white/10 p-3 text-sm">Upload audio<input type="file" aria-label="Upload dialect reference" accept="audio/*,.m4a" disabled={busy||recording||disabled||!!pending} className="mt-2 block w-full text-xs" onChange={e=>{setWordTarget(null);setFile(e.target.files?.[0]||null);setCandidates([]);}}/></label><button type="button" aria-label={recording?'Stop dialect recording':'Record dialect reference'} disabled={busy||disabled||!!pending} onClick={()=>recording?recorder.current?.stop():void start()} className="flex min-h-11 items-center gap-2 rounded-lg border border-[#E7C477]/30 px-3 text-[#E7C477]">{recording?<Square size={16}/>:<Mic size={16}/>} {recording?'Stop':'Record'}</button></div>
 {file&&!wordTarget&&<><p className="text-xs text-zinc-400">{file.name} · Record up to two minutes. Analysis uses Gemini credits. Original audio is retained in your account until deleted.</p><audio ref={playback} controls src={audioUrl} className="w-full"/><button type="button" disabled={busy||recording||disabled||!!pending||!loaded} onClick={()=>void analyze()} className="min-h-11 rounded-lg bg-[#E7C477] px-4 text-sm text-black">{busy?'Working…':'Analyze reference'}</button></>}
 {references.length>0&&<details><summary className="min-h-11 cursor-pointer py-3 text-sm text-zinc-300">Reference recordings ({references.length})</summary>{references.map(r=><div key={r.id} className="border-t border-white/10 py-1"><div className="flex items-center justify-between gap-2 text-xs text-zinc-400"><span>{r.name} · {r.status}</span><button type="button" disabled={busy||recording} onClick={()=>{setReviewResult({id:r.id,name:r.name,status:'loading'});void run(async()=>{const controller=scope.current!;const data=await request(id,'/recordings/'+r.id,{signal:controller.signal});if(controller.signal.aborted)return;setCandidates(data.candidates||[]);setReviewResult({id:r.id,name:r.name,status:data.status});});}} className="min-h-11 text-[#E7C477]">{busy&&reviewResult?.id===r.id?'Loading…':'Review'}</button><button type="button" disabled={busy||recording} onClick={()=>void run(async()=>{await request(id,'/recordings/'+r.id,{method:'DELETE',signal:scope.current!.signal});setReferences(rows=>rows.filter(v=>v.id!==r.id));})} className="min-h-11 text-zinc-400">Delete audio</button></div>{reviewResult?.id===r.id&&<div role="status" className="mb-2 rounded-lg border border-white/10 bg-white/5 p-3 text-sm text-zinc-300">{busy?'Loading recording review…':reviewResult.status==='ready'?unapprovedDialectCandidates(candidates,profile,wordTarget?.id).length?`${unapprovedDialectCandidates(candidates,profile,wordTarget?.id).length} suggestions remain to review below.`:'Review complete. No pending suggestions for this recording. Your approved corrections are saved.':reviewResult.status==='loading'?'Review could not load. Try Review again.':'Analysis is not complete yet. Check its status before adding another recording.'}{!busy&&profile.rules.length>0&&<button type="button" onClick={()=>{if(approvedDetails.current){approvedDetails.current.open=true;approvedDetails.current.scrollIntoView({block:'nearest',behavior:'smooth'});}}} className="mt-2 block min-h-11 text-[#E7C477]">View approved corrections ({profile.rules.length})</button>}</div>}</div>)}</details>}

 {pending&&<div className="flex flex-wrap gap-3"><button type="button" disabled={busy} onClick={()=>void check()} className="min-h-11 text-sm text-[#E7C477]">Check analysis status</button><button type="button" disabled={busy} onClick={()=>{setPending('');setFile(null);accountLocalStorage.removeItem('dialect-pending:'+id);}} className="min-h-11 text-xs text-zinc-400">Set aside · add another reference</button></div>}
 {unapprovedDialectCandidates(candidates,profile,wordTarget?.id).length>0&&<p className="text-xs text-zinc-400">Suggestions need your listening check. Edit any mistaken interpretation before approval.</p>}
 {unapprovedDialectCandidates(candidates,profile,wordTarget?.id).map(r=><div key={r.id} className="space-y-2 rounded-lg bg-white/5 p-3"><p className="text-xs text-[#E7C477]">{r.kind==='pronunciation'?'Pronunciation':'Word choice'}</p><input aria-label="Suggested word" disabled={busy||recording} dir="auto" value={r.word} maxLength={160} onChange={e=>setCandidates(rows=>rows.map(v=>v.id===r.id?{...v,word:e.target.value}:v))} className="min-h-11 w-full rounded-lg bg-black/25 p-2"/><input aria-label="Suggested correction" disabled={busy||recording} dir="auto" value={r.replacement} maxLength={200} onChange={e=>setCandidates(rows=>rows.map(v=>v.id===r.id?{...v,replacement:e.target.value}:v))} className="min-h-11 w-full rounded-lg bg-black/25 p-2"/><p dir="auto" className="text-xs text-zinc-400">{r.example}</p><div className="flex flex-wrap gap-3">{recordButton(r)}{onPreview&&<button type="button" disabled={busy||disabled||recording} onClick={()=>void preview(r)} className="min-h-11 text-[#E7C477]"><Play size={15} className="mr-1 inline"/>{busy&&previewRuleId===r.id?'Preparing…':'Listen'}</button>}<button type="button" disabled={busy||disabled||recording} onClick={()=>void save(r)} className="min-h-11 text-[#E7C477]">Approve</button><button type="button" disabled={busy||recording} onClick={()=>void run(async()=>{await request(id,'/recordings/'+r.recordingId+'/review',{method:'PUT',body:JSON.stringify({candidateIds:[r.id]}),signal:scope.current!.signal});setCandidates(rows=>rows.filter(v=>v.id!==r.id));})} className="min-h-11 text-zinc-400">Dismiss</button></div>{wordRecorder(r.id)}{previewPlayer(r.id)}</div>)}
 <details><summary className="min-h-11 cursor-pointer py-3 text-sm text-zinc-300">Add a correction manually</summary><select aria-label="Correction type" value={manual.kind} onChange={e=>setManual({...manual,kind:e.target.value as DialectRule['kind']})} className="min-h-11 w-full rounded-lg bg-[#151515] p-2"><option value="wording">Word choice</option><option value="pronunciation">Pronunciation</option></select><input aria-label="Dialect word" placeholder="Word to change" value={manual.word} maxLength={160} onChange={e=>setManual({...manual,word:e.target.value})} className="my-2 min-h-11 w-full rounded-lg bg-black/25 p-2"/><input aria-label="Dialect replacement" placeholder="Preferred word or vowel-marked pronunciation" value={manual.replacement} maxLength={200} onChange={e=>setManual({...manual,replacement:e.target.value})} className="min-h-11 w-full rounded-lg bg-black/25 p-2"/><button type="button" disabled={busy||disabled||!loaded||!manual.word.trim()||!manual.replacement.trim()} onClick={()=>void save(manual)} className="min-h-11 text-[#E7C477]">Save correction</button></details>
 <details ref={approvedDetails}><summary className="min-h-11 cursor-pointer py-3 text-sm text-zinc-300">Approved corrections ({profile.rules.length})</summary>{profile.rules.map(r=><div key={r.id} className="flex flex-wrap items-center gap-2 border-t border-white/10 py-2"><span dir="auto" className="min-w-0 flex-1 text-sm">{r.word} → {r.replacement}<small className="block text-zinc-400">{r.kind==='pronunciation'?'Pronunciation':'Word choice'}</small></span>{recordButton(r)}{onPreview&&<button type="button" aria-label={`Listen to ${r.word}`} disabled={busy||disabled||recording} onClick={()=>void preview(r)} className="size-11 text-[#E7C477]"><Play size={16}/></button>}<button type="button" aria-label={`Remove dialect correction ${r.word}`} disabled={busy||disabled||recording} onClick={()=>void save(undefined,r.id)} className="size-11 text-zinc-400"><Trash2 size={16}/></button><div className="w-full">{wordRecorder(r.id)}{previewPlayer(r.id)}</div></div>)}</details>
 {undo&&<button type="button" disabled={busy} onClick={()=>void save(undo,undefined,true)} className="min-h-11 text-[#E7C477]">Undo last removal</button>}{error&&<div><p role="alert" className="text-xs text-amber-300">{error}</p><button type="button" disabled={busy} onClick={()=>void run(async()=>{const controller=scope.current!;const data=await request(id,'',{signal:controller.signal});if(!controller.signal.aborted){setProfile(data);setLoaded(true);}})} className="min-h-11 text-xs text-[#E7C477]">Reload corrections</button></div>}
 </div></details>;
}
