import {useEffect,useRef,useState} from 'react';
import {api} from '../services/apiService';
import {accountLocalStorage} from '../utils/accountStorage';
import VoiceRemix from './VoiceRemix';

const panels = {design:'Voice Design',remix:'Remix',changer:'Voice Changer',isolate:'Clean audio',library:'Voice Library',professional:'Professional Clone',dictionaries:'Dictionaries',account:'Account'};
export default function ElevenLabsVoiceTools({voiceId,voiceName,onSelect,dictionaries,onDictionaries}:{voiceId:string;voiceName:string;onSelect(voice:{voiceId:string;name:string}):Promise<void>;dictionaries:Array<{pronunciation_dictionary_id:string;version_id:string}>;onDictionaries(value:Array<{pronunciation_dictionary_id:string;version_id:string}>):void}) {
  const [panel,setPanel]=useState<keyof typeof panels>('design');
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<any>(null);
  const [name,setName]=useState(`${voiceName} voice`),[audio,setAudio]=useState<string[]>([]),[fileNames,setFileNames]=useState<string[]>([]);
  const [removeNoise,setRemoveNoise]=useState(false),[ownVoice,setOwnVoice]=useState(false),[pvcId,setPvcId]=useState('');
  const [search,setSearch]=useState(''),[page,setPage]=useState(0),[library,setLibrary]=useState<any>(null),[subscription,setSubscription]=useState<any>(null);
  const [word,setWord]=useState(''),[replacement,setReplacement]=useState(''),[ruleType,setRuleType]=useState('alias'),[rules,setRules]=useState<any[]>([]);
  const [challenge,setChallenge]=useState(''),[recording,setRecording]=useState(false);
  const [pending,setPending]=useState<{id:string;action:string}|null>(()=>{try{return JSON.parse(accountLocalStorage.getItem('eleven-tools-pending')||'null');}catch{return null;}});
  const lock=useRef(false),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),mounted=useRef(true),players=useRef<HTMLAudioElement[]>([]);
  useEffect(()=>{mounted.current=true;return ()=>{mounted.current=false;if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());players.current.forEach(p=>p.pause());};},[]);
  useEffect(()=>{players.current.forEach(p=>p.pause());setResult(null);setError('');},[panel,voiceId]);
  const disabled=busy || recording || !!pending;
  const voiceStatus=result?.data?.fine_tuning;
  const registerPlayer=(el:HTMLAudioElement|null)=>{if(el&&!players.current.includes(el))players.current.push(el);};
  const message=(e:unknown)=>e instanceof Error?e.message:'Voice tool unavailable.';
  async function load(kind:string,params:Record<string,string>={}) {
    if(lock.current)return;lock.current=true;setBusy(true);setError('');
    try{const data=await api.voice.elevenLabsToolData(kind,params);if(!mounted.current)return;if(kind==='library')setLibrary(data);else if(kind==='subscription')setSubscription(data);else if(kind==='captcha')setChallenge(data.audioUrl);else setResult({status:'ready',data});}catch(e){if(mounted.current)setError(message(e));}finally{lock.current=false;if(mounted.current)setBusy(false);}
  }
  async function run(action:string,extra:Record<string,any>={}) {
    if(lock.current || disabled)return;lock.current=true;setBusy(true);setError('');setResult(null);
    const operation={id:crypto.randomUUID(),action};setPending(operation);accountLocalStorage.setItem('eleven-tools-pending',JSON.stringify(operation));
    try {
      const data=await api.voice.runElevenLabsTool({operationId:operation.id,action,...extra});
      if(!mounted.current)return;setResult(data);
      if(data.status==='ready'||data.status==='failed'){setPending(null);accountLocalStorage.removeItem('eleven-tools-pending');}
      if(action==='pvc-create'&&data.voiceId)setPvcId(data.voiceId);
      if(action==='library-add'&&data.voiceId)await onSelect({voiceId:data.voiceId,name:extra.name});
    }catch(e){if(mounted.current){setError(message(e));const status=(e as any)?.status;if(status && status<500){setPending(null);accountLocalStorage.removeItem('eleven-tools-pending');}}}
    finally{lock.current=false;if(mounted.current)setBusy(false);}
  }
  async function check() {
    if(!pending||lock.current)return;lock.current=true;setBusy(true);setError('');
    try{const data=await api.voice.elevenLabsToolStatus(pending.id);setResult(data);if(data.status==='ready'||data.status==='failed'){if(pending.action==='pvc-create'&&data.voiceId)setPvcId(data.voiceId);setPending(null);accountLocalStorage.removeItem('eleven-tools-pending');}}catch(e){setError(message(e));}finally{lock.current=false;setBusy(false);}
  }
  async function chooseFiles(files:FileList|null) {
    if(!files)return;try{const chosen=Array.from(files);if(chosen.some(f=>f.size>30*1024*1024))throw new Error('Use audio files up to 30 MB each.');const values=await Promise.all(chosen.map(f=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Could not read the recording.'));reader.readAsDataURL(f);})));setAudio(values);setFileNames(chosen.map(f=>f.name));setResult(null);}catch(e){setError(message(e));}
  }
  async function toggleRecording() {
    if(recording){recorder.current?.stop();return;}
    try{const media=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=media;const chunks:Blob[]=[];const rec=new MediaRecorder(media);recorder.current=rec;rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onstop=()=>{media.getTracks().forEach(t=>t.stop());if(!mounted.current)return;setRecording(false);const blob=new Blob(chunks,{type:rec.mimeType});const file=new File([blob],'Voice recording.webm',{type:rec.mimeType});const dt=new DataTransfer();dt.items.add(file);void chooseFiles(dt.files);};rec.start();setRecording(true);}catch(e){setError(message(e));}
  }
  const audioInput=<div className="space-y-2"><label className="block text-sm">Recording<input type="file" accept="audio/*,.m4a,.mp3,.wav,.webm" multiple={panel==='professional'} disabled={disabled} onChange={e=>void chooseFiles(e.target.files)} className="mt-1 block w-full text-sm"/></label><button type="button" disabled={busy || !!pending} onClick={()=>void toggleRecording()} className="min-h-11 rounded-xl border border-white/15 px-3">{recording?'■ Stop recording':'🎙 Record'}</button>{fileNames.length>0&&<p className="text-xs text-zinc-400">{fileNames.join(', ')}</p>}</div>;
  const button=(label:string,action:string,extra:any,blocked=false)=><button type="button" disabled={disabled||blocked} onClick={()=>void run(action,extra)} className="min-h-11 rounded-xl border border-[#E7C477]/40 px-4 text-sm text-[#E7C477] disabled:opacity-40">{label}</button>;
  return <section aria-label="ElevenLabs voice tools" className="space-y-4 rounded-2xl border border-white/10 p-4">
    <h3 className="font-semibold">ElevenLabs voice tools</h3><p className="text-xs text-zinc-400">Uses your connected ElevenLabs account. Generation uses credits; plan and permissions determine availability. Previewing never replaces your persona’s saved voice.</p>
    <nav aria-label="ElevenLabs tools" className="flex flex-wrap gap-2">{Object.entries(panels).map(([key,label])=><button type="button" key={key} aria-pressed={panel===key} disabled={recording || busy} onClick={()=>setPanel(key as keyof typeof panels)} className={`min-h-11 rounded-xl px-3 text-sm ${panel===key?'bg-white/10 text-[#E7C477]':'text-zinc-400'}`}>{label}</button>)}</nav>
    {panel==='design'&&<VoiceRemix expanded mode="design" voiceName={voiceName} disabled={busy || !!pending} onApply={onSelect}/>}
    {panel==='remix'&&<VoiceRemix expanded voiceId={voiceId} voiceName={voiceName} disabled={busy || !!pending} onApply={onSelect}/>}
    {(panel==='changer'||panel==='isolate')&&<div className="space-y-3"><p className="text-sm">{panel==='changer'?'Convert your recording into the selected voice using multilingual Voice Changer. The recording’s delivery guides this clip; it does not train future calls.':'Remove background noise from a recording before cloning or using Voice Changer.'}</p>{audioInput}{panel==='changer'&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={removeNoise} onChange={e=>setRemoveNoise(e.target.checked)} disabled={disabled}/>Remove background noise</label>}{button(panel==='changer'?'Convert into selected voice':'Clean recording',panel==='changer'?'changer':'isolate',{audio,voiceId,removeNoise},!audio.length||(panel==='changer'&&!voiceId))}</div>}
    {panel==='library'&&<div className="space-y-3"><label className="block text-sm">Search community voices<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Arabic, Jordanian, warm…" className="premium-input mt-1 w-full p-3"/></label><button type="button" disabled={busy} onClick={()=>{setPage(0);void load('library',{search,page:'0'});}} className="min-h-11 text-[#E7C477]">Search voices</button>{library?.voices?.map((v:any)=><div key={v.voice_id} className="space-y-2 rounded-xl bg-white/5 p-3"><p>{v.name} · {v.language} · {v.accent}</p><p className="text-xs text-zinc-400">{v.description}{v.rate && v.rate!==1?` · Credit multiplier: ${v.rate}×`:''}</p>{v.preview_url&&<audio ref={el=>{if(el&&!players.current.includes(el))players.current.push(el);}} controls src={v.preview_url} onPlay={e=>players.current.forEach(p=>{if(p!==e.currentTarget)p.pause();})} className="w-full"/>}{button('Add to my voices & select','library-add',{voiceId:v.voice_id,publicOwnerId:v.public_owner_id,name:v.name})}</div>)}{library&&<div className="flex gap-4"><button disabled={busy||page===0} onClick={()=>{setPage(page-1);void load('library',{search,page:String(page-1)});}}>Previous</button><button disabled={busy||!library.has_more} onClick={()=>{setPage(page+1);void load('library',{search,page:String(page+1)});}}>Next</button></div>}</div>}
    {panel==='professional'&&<div className="space-y-3"><p className="text-sm">Professional Cloning trains a voice from longer recordings and requires the speaker’s verification. For fictional character voices, use Instant Cloning, Design or Remix.</p><label className="block text-sm">Voice name<input value={name} disabled={disabled} onChange={e=>setName(e.target.value)} className="premium-input mt-1 w-full p-3"/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={ownVoice} disabled={disabled} onChange={e=>setOwnVoice(e.target.checked)}/>I’m cloning my own voice and will complete verification.</label>{button('1. Create Arabic professional clone','pvc-create',{name,language:'ar',ownVoice},!ownVoice||!name.trim())}<label className="block text-sm">Professional voice ID<input value={pvcId} disabled={disabled} onChange={e=>setPvcId(e.target.value)} placeholder="Created here or copied from My Voices" className="premium-input mt-1 w-full p-3"/></label>{audioInput}<div className="flex flex-wrap gap-3">{button('2. Upload training samples','pvc-samples',{voiceId:pvcId,audio,removeNoise},!pvcId||!audio.length)}<button type="button" disabled={busy||!pvcId} onClick={()=>void load('captcha',{voiceId:pvcId})} className="min-h-11 text-[#E7C477]">3. Get verification challenge</button></div>{challenge&&<><audio controls src={challenge} className="w-full"/><p className="text-xs text-zinc-400">Listen to the challenge, record yourself repeating it, then submit that recording.</p>{button('Submit verification recording','pvc-verify',{voiceId:pvcId,audio},audio.length!==1)}</>}<div className="flex flex-wrap gap-3">{button('4. Start training','pvc-train',{voiceId:pvcId},!pvcId)}<button type="button" disabled={busy||!pvcId} onClick={()=>void load('voice',{voiceId:pvcId})} className="min-h-11 text-[#E7C477]">Check voice status</button></div><p className="text-xs text-zinc-400">After training finishes, refresh My Voices and audition before saving it to a persona.</p></div>}
    {panel==='dictionaries'&&<div className="space-y-3"><p className="text-sm">Create aliases or IPA rules. Supported phoneme alphabets and languages depend on the speech model; audition Arabic rules before applying them.</p><input aria-label="Dictionary name" value={name} onChange={e=>setName(e.target.value)} className="premium-input w-full p-3"/><input aria-label="Word" dir="auto" value={word} onChange={e=>setWord(e.target.value)} placeholder="Word" className="premium-input w-full p-3"/><input aria-label="Pronunciation" dir="auto" value={replacement} onChange={e=>setReplacement(e.target.value)} placeholder="Pronunciation alias or IPA" className="premium-input w-full p-3"/><select aria-label="Rule type" value={ruleType} onChange={e=>setRuleType(e.target.value)} className="premium-input p-3"><option value="alias">Alias / vowel-marked spelling</option><option value="phoneme">IPA phoneme</option></select><button type="button" disabled={disabled||!word.trim()||!replacement.trim()} onClick={()=>{setRules([...rules,{word,replacement,type:ruleType}]);setWord('');setReplacement('');}} className="min-h-11 px-3 text-[#E7C477]">Add rule</button>{rules.map((r,i)=><div key={i} className="flex justify-between gap-2 text-sm"><span>{r.word} → {r.replacement}</span><button disabled={disabled} onClick={()=>setRules(rules.filter((_,j)=>j!==i))}>Remove</button></div>)}{button('Create dictionary','dictionary-create',{name,rules},!rules.length||!name.trim())}<button type="button" disabled={busy} onClick={()=>void load('dictionaries')} className="min-h-11 px-3 text-[#E7C477]">Refresh account dictionaries</button></div>}
    {panel==='account'&&<div className="space-y-3"><button type="button" disabled={busy} onClick={()=>void load('subscription')} className="min-h-11 text-[#E7C477]">Check plan & credits</button>{subscription&&<div className="space-y-1 text-sm"><p>Plan: {subscription.tier}</p><p>Characters used: {subscription.character_count} / {subscription.character_limit}</p><p>Instant Cloning: {subscription.can_use_instant_voice_cloning?'Included':'Unavailable'}</p><p>Professional Cloning: {subscription.can_use_professional_voice_cloning?'Included':'Unavailable'}</p></div>}</div>}
    {panel==='dictionaries'&&<div className="space-y-2">{dictionaries.map(d=><div key={d.pronunciation_dictionary_id} className="flex justify-between gap-2 text-xs"><span>Selected: {d.pronunciation_dictionary_id}</span><button onClick={()=>onDictionaries(dictionaries.filter(x=>x!==d))}>Remove</button></div>)}{[...(result?.dictionaryId?[{id:result.dictionaryId,version_id:result.versionId,name:'New dictionary'}]:[]),...(result?.data?.pronunciation_dictionaries || [])].map((d:any)=><button type="button" key={d.id} disabled={dictionaries.length>=3 || dictionaries.some(x=>x.pronunciation_dictionary_id===d.id)} onClick={()=>onDictionaries([...dictionaries,{pronunciation_dictionary_id:d.id,version_id:d.version_id}])} className="min-h-11 text-sm text-[#E7C477]">Use {d.name || d.id} for selected voice</button>)}</div>}
    {busy&&<p role="status" className="text-sm">Working…</p>}{error&&<p role="alert" className="text-sm text-amber-300">{error}</p>}{result?.message&&<p role="status" className="text-sm">{result.message}</p>}{result?.audioUrl&&<><audio ref={registerPlayer} controls src={result.audioUrl} className="w-full"/><a download="ElevenLabs-recording" href={result.audioUrl} className="inline-block min-h-11 text-[#E7C477]">Download recording</a></>}{panel==='professional'&&result?.data&&<div role="status" className="space-y-2 rounded-xl bg-white/5 p-3 text-sm"><p>{result.data.name || 'Professional voice'} · {result.data.samples?.length || 0} samples</p><p>Verification: {result.data.voice_verification?.is_verified || voiceStatus?.is_verified?'Verified':'Not yet verified'}</p>{Object.entries(voiceStatus?.state || {}).map(([model,state])=><p key={model}>{model}: {String(state)}</p>)}{voiceStatus?.message&&<p>{String(voiceStatus.message)}</p>}</div>}{pending&&<button type="button" disabled={busy} onClick={()=>void check()} className="min-h-11 text-[#E7C477]">Check pending operation</button>}
  </section>;
}
