export const COVER_LIBRARY = {
 outfit:[{id:'leather',name:'Leather jacket',image:'/wardrobe/outfit-leather-moto.jpg',prompt:'a leather motorcycle jacket with a casual outfit'},{id:'gym',name:'Activewear',image:'/wardrobe/outfit-sculpt-gym.jpg',prompt:'fitted athletic activewear'},{id:'evening',name:'Emerald evening dress',image:'/wardrobe/outfit-emerald-slit.jpg',prompt:'an emerald green evening dress with a side slit'},{id:'satin',name:'Satin slip dress',image:'/wardrobe/outfit-satin-slip.jpg',prompt:'a satin slip dress'}],
 background:[{id:'cafe',name:'Paris café',image:'/examples/showcase_parisian_chic.png',prompt:'at an outdoor Paris café'},{id:'coast',name:'Amalfi coast',image:'/examples/showcase_amalfi_villa.png',prompt:'on a terrace overlooking the Amalfi coast'},{id:'studio',name:'Photo studio',image:'/examples/showcase_studio_beauty.png',prompt:'in a clean professional photography studio'}],
 angle:[{id:'front',name:'Eye level',image:'/demo/camera-angle-front.jpg',prompt:'eye-level camera, front-facing portrait'},{id:'side',name:'Side profile',image:'/demo/camera-angle-side.jpg',prompt:'side-profile camera view'},{id:'low',name:'Low angle',image:'/isabella_laurent_low_angle.png',prompt:'camera below eye level, looking slightly upward'},{id:'high',name:'High angle',image:'/isabella_laurent_high_angle.png',prompt:'camera above eye level, looking slightly downward'}],
 hair:[{id:'waves',name:'Loose waves',prompt:'hair styled in loose flowing waves'},{id:'straight',name:'Sleek straight',prompt:'sleek straight hair'},{id:'bun',name:'Sleek bun',prompt:'hair pulled into a sleek bun'},{id:'pony',name:'High ponytail',prompt:'hair in a high ponytail'},{id:'bob',name:'Short bob',prompt:'a chin-length bob haircut'},{id:'curls',name:'Natural curls',prompt:'defined natural curly hair'}],
 lighting:[{id:'golden',name:'Golden hour',prompt:'warm golden-hour sunlight'},{id:'soft',name:'Soft daylight',prompt:'soft natural window light'},{id:'night',name:'Cinematic night',prompt:'cinematic nighttime lighting'}],
 pose:[{id:'standing',name:'Standing',prompt:'a relaxed standing pose'},{id:'seated',name:'Seated',prompt:'a naturally seated pose'},{id:'walking',name:'Walking',prompt:'a candid walking pose'}]
} as const;
export type CoverChoices=Partial<Record<keyof typeof COVER_LIBRARY,string>>;
export function normalizeCoverChoices(value:any):CoverChoices{
 const result:CoverChoices={};for(const key of Object.keys(COVER_LIBRARY) as (keyof CoverChoices)[]){if(COVER_LIBRARY[key].some(p=>p.id===value?.[key]))result[key]=value[key];}return result;
}
export function coverGenerationPrompt(description:string,choices:CoverChoices){
 const selected=normalizeCoverChoices(choices);const directions=(Object.keys(selected) as (keyof CoverChoices)[]).map(k=>COVER_LIBRARY[k].find(p=>p.id===selected[k])!.prompt);
 return `Create a new cover photograph using the reference photo for the person's identity, not as the finished composition. Preserve facial identity. Change the styling and scene according to the instructions below. For unspecified details, keep the reference appearance. Style choices: ${directions.join('; ')||'keep reference styling'}. User's desired photo: ${description.trim()||'Create a polished, natural portrait with the selected styling.'}. User details take priority if they conflict with a style choice. Return one photograph, with no added text, watermarks, borders, or collage.`;
}
