import { callLanguageInstructions, type CallPreferences } from './voiceCallPreferences';
export const ARABIC_DIALECTS = {
 'jordanian-syrian': 'Jordanian–Syrian · أردني سوري', jordanian: 'Jordanian · أردني', syrian: 'Syrian · سوري', lebanese: 'Lebanese · لبناني', palestinian: 'Palestinian · فلسطيني', egyptian: 'Egyptian · مصري', gulf: 'Gulf Arabic · خليجي', msa: 'Modern Standard Arabic · فصحى',
} as const;
export type SpokenLanguage='ar'|'en'|'fr'|'es'|'de'|'tr'|'it'|'pt'|'hi'|'ja'|'ko';
export type ArabicDialect=keyof typeof ARABIC_DIALECTS;
export type LanguageProfile={callPreferences?:CallPreferences;personalitySettings?:{language?:unknown;dialect?:unknown}|null};
export function normalizeLanguage(p:LanguageProfile){const s=p?.personalitySettings;return {language:typeof s?.language==='string'&&['ar','en','fr','es','de','tr','it','pt','hi','ja','ko'].includes(s.language)?s.language as SpokenLanguage:'en' as SpokenLanguage,dialect:typeof s?.dialect==='string'&&Object.prototype.hasOwnProperty.call(ARABIC_DIALECTS,s.dialect)?s.dialect as ArabicDialect:'jordanian-syrian' as ArabicDialect};}
export function recognitionLanguage(p:LanguageProfile){const s=normalizeLanguage(p);const locales:Record<ArabicDialect,string>={'jordanian-syrian':'ar-JO',jordanian:'ar-JO',syrian:'ar-SY',lebanese:'ar-LB',palestinian:'ar-PS',egyptian:'ar-EG',gulf:'ar-SA',msa:'ar-SA'};return {scribe:s.language,browser:s.language==='ar'?locales[s.dialect]:({en:'en-US',fr:'fr-FR',es:'es-ES',de:'de-DE',tr:'tr-TR',it:'it-IT',pt:'pt-BR',hi:'hi-IN',ja:'ja-JP',ko:'ko-KR'}[s.language]||'en-US')};}
export function languageInstructions(p:LanguageProfile):string{if(p.callPreferences)return callLanguageInstructions(p.callPreferences);const s=normalizeLanguage(p);if(s.language!=='ar'&&s.language!=='en')return `Preferred conversation language: ${s.language}. Follow explicit language and accent requests.`;if(s.language==='en')return 'Preferred conversation language: English. Follow an explicit request to switch languages.';return `Preferred conversation language: Arabic. Use ${ARABIC_DIALECTS[s.dialect]} naturally, with everyday conversational phrasing and no exaggerated dialect performance. ${s.dialect==='jordanian-syrian'||s.dialect==='jordanian'?'Use urban Jordanian speech'+(s.dialect==='jordanian-syrian'?' with a light Syrian influence':'')+'; colloquial qaf is a glottal stop (hamza), not g. Keep ك as k, not ch, and ج as j, not y. Avoid Saudi/Gulf wording such as وش، الحين، أبغى; prefer شو، هلأ، بدي. When the caller corrects pronunciation, acknowledge the intended sound rather than repeating two identical written words.':''} Keep proper names and model names in their original form. Preserve the existing persona identity. Follow an explicit request to switch languages.`;}
