export type VoiceCloningModel = { id: string; name: string; provider: string; kind: 'reference' | 'enrollment' | 'preset' | 'singing' | 'unavailable'; description: string; model?: string; aliases?: string[]; transcriptRequired?: boolean; voices?: string[] };
export const VOICE_CLONING_MODELS: VoiceCloningModel[] = [
 {id:'elevenlabs',name:'ElevenLabs Instant Voice Clone',provider:'ElevenLabs',kind:'enrollment',description:'Create a reusable ElevenLabs voice for speech and live calls. Compatible with ElevenLabs v2 and v3 speech models.',aliases:['elevenlabs-v3','elevenlabs-v2']},
 {id:'wavespeed:zonos2',name:'Zyphra Zonos2',provider:'WaveSpeed',kind:'reference',model:'wavespeed-ai/zonos2',description:'Generate speech using the primary reference recording.',aliases:['zonos2']},
 {id:'wavespeed:qwen3-clone',name:'Qwen3-TTS Voice Clone',provider:'WaveSpeed',kind:'reference',model:'wavespeed-ai/qwen3-tts/voice-clone',description:'Reference-based speech with an optional recording transcript. Arabic is not a listed output language.',aliases:['qwen3-clone']},
 {id:'wavespeed:seed-speech',name:'ByteDance Seed Speech 2.0',provider:'WaveSpeed',kind:'preset',model:'bytedance/seed-speech-tts-2.0',description:'Preset voices with delivery instructions. This API does not clone uploaded recordings.',aliases:['seed-speech'],voices:['stokie_en','dacey_en','tim_en','kian_en_zh','sophie_en_zh','vivi_mixed_en_zh_ja_es_id']},
 {id:'wavespeed:omnivoice',name:'OmniVoice',provider:'WaveSpeed',kind:'reference',model:'wavespeed-ai/omnivoice/voice-clone',description:'Multilingual speech from a primary voice reference, with optional transcript and speed control.',aliases:['omnivoice']},
 {id:'playht',name:'PlayHT / PlayAI',provider:'PlayHT',kind:'unavailable',description:'The old ElevenLabs label did not connect to PlayHT. A separate PlayHT integration is required.',aliases:['elevenlabs:playht']},
 {id:'fal:f5-tts',name:'F5-TTS',provider:'Fal',kind:'reference',model:'fal-ai/f5-tts',description:'Voice cloning from reference audio through the Fal API. An optional transcript improves matching.',aliases:['elevenlabs:f5-tts','f5-tts']},
 {id:'mureka-vocal',name:'Mureka Vocal Clone',provider:'WaveSpeed',kind:'singing',model:'mureka-ai/vocal-clone',description:'Create a singing voice ID for Mureka music generation. It cannot be used for spoken calls.',aliases:['elevenlabs:mureka-vocal']},
 {id:'wiro-voice:openmoss/moss-tts-v1-5',name:'OpenMOSS MOSS-TTS v1.5',provider:'Wiro',kind:'reference',model:'openmoss/moss-tts-v1-5',description:'Multilingual speech using your reference recording.'},
 {id:'wiro-voice:k2-fsa/omnivoice',name:'OmniVoice',provider:'Wiro',kind:'reference',model:'k2-fsa/omnivoice',description:'Multilingual reference-based speech with transcript and speed controls.'},
 {id:'wiro-voice:resemble-ai/chatterbox-multilingual',name:'Resemble AI Chatterbox Multilingual',provider:'Wiro',kind:'reference',model:'resemble-ai/chatterbox-multilingual',description:'Expressive reference-based speech, including Arabic.'},
 {id:'wiro-voice:openbmb/voxcpm2',name:'OpenBMB VoxCPM2',provider:'Wiro',kind:'reference',model:'openbmb/voxcpm2',description:'Copy the reference speaker’s timbre without a transcript. Use 5–15 seconds of clear speech.'},
 {id:'wiro-voice:fishaudio/s2-pro',name:'Fish Audio S2 Pro',provider:'Wiro',kind:'reference',model:'fishaudio/s2-pro',description:'Reference-based speech with expressive delivery. Requires the recording’s exact transcript.',transcriptRequired:true},
 {id:'openai:tts',name:'OpenAI Nova / Onyx TTS',provider:'OpenAI',kind:'preset',description:'Choose an OpenAI stock voice. This existing TTS integration does not clone recordings.',voices:['nova','onyx','alloy','echo','fable','shimmer']},
 {id:'minimax-clone',name:'MiniMax Voice Clone',provider:'WaveSpeed',kind:'enrollment',model:'minimax/voice-clone',description:'Create a reusable MiniMax voice and validate it with a speech preview.'},
 {id:'chatterbox',name:'Chatterbox TTS',provider:'WaveSpeed',kind:'reference',model:'chatterbox/text-to-speech',description:'Speech from a reference recording with expression control.'},
 {id:'qwen-tts',name:'Qwen3-TTS Preset Voices',provider:'WaveSpeed',kind:'preset',model:'wavespeed-ai/qwen3-tts/text-to-speech',description:'Generate speech with a Qwen preset voice.',voices:['Vivian','Serena','Ryan','Aiden']},
];
export const voiceCloningModel = (id: unknown): VoiceCloningModel | undefined => typeof id === 'string' ? VOICE_CLONING_MODELS.find(model=>model.id===id || model.aliases?.includes(id)) : undefined;
